### ISSUE TITLE
better error messages, eg: report indexes and shape instead of static text

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#1]
these error messages are not very helpful for debugging:
https://github.com/DlangScience/mir/blob/master/source/mir/ndslice/slice.d#L854 [+ elsewhere similar]

```
assert(_indexes[0][i] < _lengths[i], "indexStride: index must be less than lengths");
```

how about instead:

```
version(assert)
  enforce(_indexes[0][i] < _lengths[i], text("indexStride: index must be less than lengths", _indexes[0][i], " ", _lengths[i], " ", i));
```

NOTE: not sure if there's a better way to do it, but i want to have the check only in -release mode (hence version(assert)), and I want to avoid runtime cost in forming a text(..) expression when the assert passes, hence the enforce(boo, lazy exp)
##

**Comment by 9il** [comment]
I can add information about position:
`[a, b, c]// a at 0 ,b at 1, and c at 2 positions`
Any exceptions or GC allocations are not allowed for Slice. ndslice is `@nogc` library except `reshape` and `sliced` (with default flag).

**Comment by timotheecour** [comment]
just wrote this: hacky but works:
formatted assert error messages inside nogc functions
http://forum.dlang.org/thread/mailman.3496.1452412496.22025.digitalmars-d@puremagic.com

while waiting for a fix to https://issues.dlang.org/show_bug.cgi?id=13055

**Comment by 9il** [comment]
`@safe` and `pure`?

**Comment by 9il** [comment]
`@safe` can be hacked with `@trusted`

**Comment by timotheecour** [comment]
and pure can be worked around in debug mode [updated thread]:

```
@nogc @trusted pure
void test(int a){
  if(!(a==3)){
    debug{
    char[100]buf; //TODO:make sure big enough
    // would like to use 'auto s=sformat(buf, "a = %s", a);' but not nogc: https://issues.dlang.org/show_bug.cgi?id=13055 
    auto m=snprintf(buf.ptr, buf.length, "a = %d", a);
    assert(m<buf.length && m>0);
    assert(0, buf[0..m]);
    }
    else{
      assert(0);
    }
  }
}
```

now this should be made into something more generic and reusable...

**Comment by 9il** [comment]
Looks like it is better to implement own function for integers in the package.

**Comment by timotheecour** [comment]
what do you mean?

**Comment by 9il** [comment]
> what do you mean?

```
const(char)[] localText(T...)(char[] buff, T values) {
///must work with integers and strings
}
```

**Comment by timotheecour** [comment]
+1 [ugly is ok while waiting for a better solution, eg rcstring or https://issues.dlang.org/show_bug.cgi?id=13055 ]

**Comment by 9il** [comment]
does not related to this repo anymore
