### ISSUE TITLE
allow strided slice indexing: m[0, 0..5, _, R(0, $, 2), R($-1, 0, -2)  ]

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#10]
discussed here: https://docs.google.com/document/d/1cEf8AynZEZxlTENJx1i4w1GTB481bbc4iUbUeJT00-U/edit#heading=h.kv2inl5g6n2a

Also note that `i..j` only works within opIndex, not within opCall (math index), so `R(i,j)` is needed for opCall (and should also be allowed for opIndex for uniformity)

Also this syntax sugar (built on top of R) is convenient:

```
enum _=R();
R(...).reverse
inclusive(a,b,-2)
```

also discussed in the doc
##

**Comment by 9il** [comment]
Syntax problem: `$` does not work with math index order.

**Comment by timotheecour** [comment]
yes, neither does slice i..j.
[although this is slightly orthogonal to this issue, which deals with opIndex]

alternatives for defining a math order (instead of opCall):

```
m[a,b,c] //C order
m(c,b,a) //math order [but issues with i..j and $], which you just implemented
m.math[c,b,a] // via a math property 
m[math,c,b,a] // via a math extra arg
```

Yet another possibility is to extend language to support $, and i..j inside opCall.

any other idea?

Independently of these limitations on opCall, there was discussion at some point to also support `i..j:stride` to avoid R(i,j,stride) but I don't remember where that went.

**Comment by 9il** [comment]
Syntax changes look good to me. One for `i..j:stride`,  and another to make `opCall` like `opIndex`.
There is wiki page for DIPs http://wiki.dlang.org/DIPs

**Comment by 9il** [comment]
wontfix in near future
