### ISSUE TITLE
fix circle doc setup

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#103]
i guess the easiest solution for now is just to host a binary of ddox?

**Comment by 9il** [comment]
No, just remove ddox build

**Comment by wilzbach** [comment]
> No, just remove ddox build

Ok, but only until we found a better doc engine :/

**Comment by 9il** [comment]
> Ok, but only until we found a better doc engine :/

I will fix harbored

**Comment by 9il** [comment]
> I will fix harbored

I have fixed bugs, but it has a lot of visual issues. So we need normal DDOC with macros from dlang.org

**Comment by wilzbach** [comment]
https://github.com/dlang/dlang.org/blob/master/html.ddoc

**Comment by wilzbach** [comment]
And https://github.com/dlang/dlang.org/blob/master/std.ddoc +
https://github.com/dlang/dlang.org/blob/97d3e5eff143c655f70008066145568b91e2a3d6/std-ddox.ddoc

Seems like a lot of files  :(

**Comment by 9il** [comment]
We should go with bootDoc thought: https://github.com/JakobOvrum/bootDoc

**Comment by 9il** [comment]
See also http://jakobovrum.github.io/bootdoc-phobos/ =) This already contains macros!!!

**Comment by wilzbach** [comment]
But this runs ddox in the background and just adds a couple of css classes?

**Comment by 9il** [comment]
No the DDOX, this is common DDOC (by DMD)

**Comment by wilzbach** [comment]
> No the DDOX, this is common DDOC (by DMD)

Ah I see  - sorry about the confusion :/

**Comment by 9il** [comment]
try `$ rdmd bootDoc/generate.d --output=docs source` from master

**Comment by 9il** [comment]
this should generate docs in folder `docs`.

**Comment by wilzbach** [comment]
hmm - did you see that?
![image](https://cloud.githubusercontent.com/assets/4370550/14580990/4b88cd66-03e9-11e6-8acb-a70bdaa551e7.png)

**Comment by wilzbach** [comment]
Apart from that I really like it :)
Btw is there a way to generate a overview or main page? 
Would be nice to have, so that I can setup the s3 integration again.

**Comment by 9il** [comment]
> hmm - did you see that?

What wrong with that?

> Btw is there a way to generate a overview or main page? 
> Would be nice to have, so that I can setup the s3 integration again.

We should generate it from a marcdown file, currently main page for reference is `mir.html`, you can change it in `settings.ddoc`

**Comment by wilzbach** [comment]
> What wrong with that?

It's pretty messy and thus hard to read.
I think the template constraints should not be bold and maybe even have a smaller font.
-> I will just submit a PR at bootdoc - do you want to maintain our own fork too?

**Comment by 9il** [comment]
Lets create fork for DlangScience and redirect submodule to it

**Comment by wilzbach** [comment]
Closing as bootdoc works now :)
