### ISSUE TITLE
notice about extensive testing in ReadMe

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#105]
Probably we want to add a small message like that once Travis and AppVeyor are fixed:

> Mir is automatically tested with recent releases of dmd and ldc for Linux, OS X and Windows x86 and x64.

**Comment by 9il** [comment]
We also need to test 32 bit linux

**Comment by wilzbach** [comment]
I think nownow we can put the notice in the wiki? Or is the fact that ldc under Windows doesn't compile a blocker?

**Comment by 9il** [comment]
Yes, we can, but with note about LDC issues. Some matrix/table would be helpful for each compiler

**Comment by wilzbach** [comment]
added with #153
