### ISSUE TITLE
mir.las.sum: assertion failure on Win64 with ldc

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#120]
It yields:

```
core.exception.AssertError@source\mir\las\sum.d(1835): Assertion failure
```

[line](https://github.com/DlangScience/mir/blob/master/source/mir/las/sum.d#L1835)
[details](https://ci.appveyor.com/project/9il/mir/build/1.0.100/job/j4sav10gb62kuhf7)

See also: #116 
##

**Comment by 9il** [comment]
This looks like LDC bug

**Comment by wilzbach** [comment]
Ok then I will add `allow_failures` temporarily to the appveyor script :(
Do you submit it to ldc?

**Comment by 9il** [comment]
> Do you submit it to ldc?

https://github.com/ldc-developers/ldc/issues/1436
