### ISSUE TITLE
Remove mir.ndslice

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#122]
After first release of LDC with `mir.ndslice.sparse` we should remove `ndslice` from mir.

See also #121  
##

**Comment by wilzbach** [comment]
> After first release of LDC with mir.ndslice.sparse we should remove ndslice from mir.

But that's why you have versions, branches and tags.
Besides what stops users when using dub to use `sci.ndslice` instead of `mir.ndslice`?

**Comment by 9il** [comment]
> Besides what stops users when using dub to use sci.ndslice instead of mir.ndslice?

This is does not matter. `ndslice` would be stable enough to build mir on top of Phobos.

**Comment by wilzbach** [comment]
> This is does not matter. ndslice would be stable enough to build mir on top of Phobos.

Ah I see and understand your logic now :)

**Comment by wilzbach** [comment]
Hmm about about renaming `mir.ndslice` to `std.experimental.ndslice`, so that merging is easier?

**Comment by 9il** [comment]
> Hmm about about renaming mir.ndslice to std.experimental.ndslice, so that merging is easier?

name conflict?

**Comment by wilzbach** [comment]
> name conflict?

Can't we solve this via `static if`?

**Comment by 9il** [comment]
> Can't we solve this via static if?

How?

**Comment by 9il** [comment]
I need modification of ndslice for sparse

**Comment by wilzbach** [comment]
> How?

Damn doesn't work :/

**Comment by wilzbach** [comment]
I got an idea - rename it to std.experimental.ndslice - so in the "std" directory (which will be excluded by default) and then configure it's optional inclusion with dub.
