### ISSUE TITLE
make template constraints smaller and grayish

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#149]
(like in the Phobos doc)

**Comment by 9il** [comment]
maybe we can just copy Phobos css?

**Comment by wilzbach** [comment]
It is a ddoc macro and defined [here](https://github.com/dlang/dlang.org/blob/master/html.ddoc#L166) - I will see whether I can import it.

> maybe we can just copy Phobos css?

Yep and all macros - that would be pretty cool! :)
