### ISSUE TITLE
indexSlice documentation

### ISSUE THREAD

**Issue by John-Colvin** [9il/dip80-ndslice#15]
What does indexSlice actually do? It's not clear to me from the documentation or the rather small unittests.

**Comment by 9il** [comment]
This is multidimensional analog of `iota(n)`. Could you please suggest something to improve the docs.

**Comment by 9il** [comment]
... to improve the docs for this function.

**Comment by 9il** [comment]
Maybe just `This is multidimensional analog of iota(n)` would be OK?

**Comment by wilzbach** [comment]
@9il how about adding these as unittests?
Might make it clearer.

```
    import std.algorithm.comparison: equal;
    import std.range: repeat;

    auto im2d = indexSlice(2, 3);
    assert(im2d.byElement.equal([[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2]]));

    auto im3d = indexSlice(3, 2);
    assert(im3d.byElement.equal([[0, 0], [0, 1], [1, 0], [1, 1], [2, 0], [2, 1]]));

    auto im7d = indexSlice(7, 2);
    assert(im7d.length == 7);
    assert(im7d.elementsCount == 7 * 2);
    assert(im7d[6].equal([[6, 0], [6, 1]]));
```

**Comment by 9il** [comment]
`==` operator should work with arrays

**Comment by wilzbach** [comment]
> == operator should work with arrays

Nope source/mir/ndslice/selection.d(1568,12): Error: incompatible types for ((byElement(im3d)) == ([[0, 0], [0, 1], [1, 0], [1, 1], [2, 0], [2, 1]])): 'ByElement' and 'int[][]'

**Comment by 9il** [comment]
ND version

``` D
auto b = slice == [[cast(size_t[2])[0, 0], cast(size_t[2])[0, 1], ...], ... ];
```

or plain

``` D
auto b = slice == [cast(size_t[2])[0, 0], cast(size_t[2])[0, 1], ...];
```

**Comment by wilzbach** [comment]
> ND version

Ah I see, but you already have such tests that use `cast`? So what's the argument against `equal`?

**Comment by 9il** [comment]
No arguments)
Would _This is multidimensional analog of iota(n)._ be clear for users?

**Comment by wilzbach** [comment]
> Would This is multidimensional analog of iota(n). be clear for users?

Imho yes, but better wait for @John-Colvin's feedback. However I do think that you should add such understandable unittests as I proposed, because they make it easier to grasp what the function actually does ;-)

**Comment by 9il** [comment]
> However I do think that you should add such understandable unittests as I proposed, because they make it easier to grasp what the function actually does ;-)

Will add)

**Comment by wilzbach** [comment]
Ping :)

**Comment by 9il** [comment]
fixed
