### ISSUE TITLE
unneeded for loop of `isPermutation`

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#155]
if you look at `isPermutation` - the `for` loop that distinguishes it from seems unnecessary.

For convenience:

```
bool isPermutation(size_t N)(auto ref in size_t[N] perm)
{
    int[N] mask;
    if (isValidPartialPermutationImpl(perm, mask) == false)
        return false;
    foreach (e; mask)
        if (e == false)
            return false;
    return true;
}

bool isValidPartialPermutation(size_t N)(in size_t[] perm)
{
    int[N] mask;
    return isValidPartialPermutationImpl(perm, mask);
}

private bool isValidPartialPermutationImpl(size_t N)(in size_t[] perm, ref int[N] mask)
{
    if (perm.length == 0)
        return false;
    foreach (j; perm)
    {
        if (j >= N)
            return false;
        if (mask[j]) //duplicate
            return false;
        mask[j] = true;
    }
    return true;
}
```

AFAICT the 
- mask has the length of the input numbers 
- the impl checks for duplicates (via the mask)
- the impl checks for numbers which are greater or equal than N (negative is not possible)

So if we have n numbers - they are all either unique (=is_permutation) or a) have duplicates or b) numbers outside the range. 
Also [code coverage ](https://codecov.io/github/DlangScience/mir/source/mir/ndslice/internal.d?ref=dc27bb8bfa651ed56c76a1a85e9cbc633d10fe2e#l-170) tells that the `return false` never gets executed.

**Comment by 9il** [comment]
> mask has the length of the input numbers

no

**Comment by wilzbach** [comment]
> mask has the length of the input numbers

Oh right, but this issue was more about the (unneeded?) `for` loop of `isPermutation` and there mask is `int[N] mask;`

**Comment by 9il** [comment]
ok

**Comment by 9il** [comment]
will fix
