### ISSUE TITLE
PtrTuple.save fails for dummyranges

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#163]
@9il - is this test better? It yes, it fails ...

```
unittest
{
    // test save with ranges behavior
    import std.internal.test.dummyrange;
    foreach (RB; AliasSeq!(ReturnBy.Reference, ReturnBy.Value))
    {
        alias R = PtrShell!(DummyRange!(RB, Length.Yes, RangeType.Random));
        R a, b, c;
        alias T = PtrTuple!("a", "b");
        alias S = T!(R, R);
        auto t = S(a, b);

        auto val = 42;
        a[1] = val;
        assert(t[1].a == val);
        c[1] = val + 1;
        auto tCopy = t.save;
        tCopy.ptrs[0] = c;

        assert(tCopy[1].a == val + 1);
        import std.stdio;
        writeln(tCopy[1].a); //43
        writeln(t[1].a); // 42
        assert(t.front.a == val);
    }
}
```

**Comment by 9il** [comment]
What behavior you test?
`save` should only save iteration (position). It may copy, may do not copy, does not matter.

**Comment by 9il** [comment]
You need a class like `ReferenceBidirectionalRange` from [Phobos](https://github.com/dlang/phobos/blob/75702dc9957996d4cdb87c65b3104ac8d0ea5e67/std/internal/test/dummyrange.d#L294) but with random access

**Comment by wilzbach** [comment]
This mistake was that all `DummyRanges` use the same array (tthus the same change) and one need to manually `reinit` them ... :/
