### ISSUE TITLE
mir.model.svm [$100]

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#166]
We are going to machine learning, hehe)

See https://www.csie.ntu.edu.tw/~cjlin/liblinear/
and https://www.csie.ntu.edu.tw/~cjlin/libsvm/
##

**Comment by wilzbach** [comment]
Do you know [sklearn](http://scikit-learn.org/stable/index.html)? I really like their API design.

**Comment by 9il** [comment]
Thank you for the link)

**Comment by wilzbach** [comment]
We probably need five more developers if we want to get all your visions done in the next two years ;-)
Any idea how we could attract man power?

**Comment by 9il** [comment]
> Any idea how we could attract man power?

We need better user experience like good documentation: text & design & navigation

**Comment by 9il** [comment]
... than we would build our next packages.  And people would happy to participate after we add 3 big packages, thought

**Comment by wilzbach** [comment]
> We need better user experience like good documentation: text & design & navigatino

Yep [mir.rocks](http://mir.rocks) is waiting for our input. Ok I will push a documentation once we have more packages ;-)

**Comment by 9il** [comment]
> Yep mir.rocks is waiting for our input. Ok I will push a documentation once we have more packages ;-)

Would be great to have doc engine up to package release, because devs reads release annonces.

**Comment by wilzbach** [comment]
> Would be great to have doc engine up to package release, because devs reads release annonces.

ETA?

**Comment by 9il** [comment]
One week for sparse or one month to the next package

**Comment by henrygouk** [comment]
What sorts of other machine learning packages do you envision being added in future? I'm just wondering whether it would be better to create mir.ml, and have a mir.ml.svm subpackage. A package like mir.ml could include some started procedures relevant to all machine learning models, such as cross validation. Other subpackages could be added in future, for example mir.ml.glm for generalised linear models, and mir.ml.nnet for neural networks.

I guess it's all a matter of preferences about how flat the structure of the library is.

**Comment by 9il** [comment]
@henrygouk I will release sparse version of`mir.model.lda.hoffman` (topic modeling). `mir.ml` can be preserved for out of the box algorithms and `mir.model` for building blocks like `svm` and `kmeans`.

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
