### ISSUE TITLE
mir.jupyter

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#169]
Integration with http://jupyter.org/
##

**Comment by wilzbach** [comment]
We probably want to develop the repl kernel at a different repo as it is independent to Mir, but this is still very important - I really like Jupyter :)
Do we then want you write our own plotting library too? :)

**Comment by 9il** [comment]
> Do we then want you write our own plotting library too? :)

Jupiter is better choice thought

**Comment by 9il** [comment]
See also https://github.com/MartinNowak/drepl

**Comment by wilzbach** [comment]
Or https://github.com/callumenator/dabble

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
