### ISSUE TITLE
create AUR package

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#170]
for convenience user install (globally like libphobos-devel) - other package managers that we should support?

**Comment by 9il** [comment]
> other package managers that we should support?

http://d-apt.sourceforge.net/

**Comment by 9il** [comment]
> other package managers that we should support?

http://d-apt.sourceforge.net/

**Comment by 9il** [comment]
Sorry, missed bottom

**Comment by 9il** [comment]
Also http://www.thebrewproject.com/ and https://www.macports.org/

**Comment by 9il** [comment]
Also 
https://img.shields.io/aur/version/libmir.svg
https://img.shields.io/aur/version/libmir-git.svg

Looks better, imho

**Comment by 9il** [comment]
fixed with #171
