### ISSUE TITLE
which twitter account

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#177]
One week ago I reserved [@dlangscience](https://twitter.com/dlangscience) - we could use that account to promote new versions & other outreach - otherwise I also reserved [@libmir](https://twitter.com/libmir) - which one do you prefer?

**Comment by 9il** [comment]
@libmir =)

**Comment by 9il** [comment]
thanks)

**Comment by wilzbach** [comment]
Okay, but then we need a logo for Mir :)

**Comment by wilzbach** [comment]
now both https://twitter.com/dlangscience and https://twitter.com/libmir are tweeting through the universe.
libmir will be used for announcements of new releases.
