### ISSUE TITLE
better access to allowDownsize

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#18]
It seems that this that the default flag for allowDownsize has been recently changed - (at least for the latest version in phobos).

This makes sense, but we should have a handy access to the flag, this is annoying!

```
iota(10).sliced!(Yes.replaceArrayWithPointer, Yes.allowDownsize)(4);
```

**Comment by 9il** [comment]
You can make an alias `alias mysliced = sliced!(Yes.replaceArrayWithPointer, Yes.allowDownsize);`

**Comment by wilzbach** [comment]
Yeah, but my point was that this is a rather common pattern and the alias should be within mir ;-)

**Comment by 9il** [comment]
The main problem is good function name)

**Comment by wilzbach** [comment]
`downsliced`?

**Comment by 9il** [comment]
> downsliced?

@John-Colvin what do you think?

@greenify John is native English speaker.

**Comment by John-Colvin** [comment]
I'm not convinced that it's necessary/beneficial to have an alias at all.

@greenify what important use-cases do you have for the Yes.allowDownsize semantics? I don't really see the value in it, but perhaps I'm not being imaginative enough

**Comment by wilzbach** [comment]
> what important use-cases do you have for the Yes.allowDownsize semantics? I don't really see the value in it, but perhaps I'm not being imaginative enough

it happened quite often to me in NumPy and my point was more that I have to select the option for `replaceArrayWithPointer` even though in most cases I don't want to bother with this option.

I can still repeat the example given above:

``` D
iota(10).sliced!(Yes.replaceArrayWithPointer, Yes.allowDownsize)(4);
```

or let's say I initially created lots of random numbers and want to seed my arrays:

```
int[] randoms = new int[1000];
// do sth. with them
randoms.downsize(3,  3);
randoms.downsize!2(3,  3, 9); //sample again from same array with shift
```

It's hard to come up with a really "good" usecase, because one can always argue: hey that's your fault.

**Comment by wilzbach** [comment]
Update: If I look through the current documentation at [Phobos](http://dlang.org/phobos/std_experimental_ndslice_iteration.html) I see this pattern to have a larger input source quite often, that's btw why I was a bit surprised when I realized that you might have changed the defaults.

So all those definitions fail and need to replaced with the bulky thing from above: 

```
1000.iota.sliced(3, 4, 5)
auto slice = new int[1000].sliced(5, 13);
// etc.
```

**Comment by wilzbach** [comment]
Closing this for now - though we shouldn't forget when we create new APIs that such template flags are dependent on the order and access to the last ones might be inconvenient ;-)
