### ISSUE TITLE
Benchmark charting tool

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#184]
We need a front-end tool for charting our benchmarks for users, which can be integrated into Mir's site. Our benchmarks probably should output JSON. And we need painless tool to upload and charts this json files.

Any thoughts?

See also http://dimplejs.org/
##

**Comment by wilzbach** [comment]
> Our benchmarks probably should output JSON

Yep we can automatically upload this to S3, enable CORS (cross-origin) and then built a nice JS frontend around it. Should be easy, however

1) Probably we will run into problems with CI if we have longer tests - AFAIK max-time is one-hour
2) most CI runs in docker (doesn't guarantee same performance for every run) 
3) What do we benchmark against?

**Comment by 9il** [comment]
See also https://github.com/tamediadigital/vibe-s3
:-)

**Comment by 9il** [comment]
> 1) Probably we will run into problems with CI if we have longer tests - AFAIK max-time is one-hour
> 2) most CI runs in docker (doesn't guarantee same performance for every run) 

Yes, we should test on local machines.

> 3) What do we benchmark against?

Against Phobos / numpy / liblinear / fftw and others.

**Comment by wilzbach** [comment]
> Yes, we should test on local machines.

Hmm I am a bit afraid that we don't want to do this on every release - at least I only have a laptop.
I probably can find a VPS somewhere that we can use for this once we have a couple of scripts ready ;-)

> https://github.com/tamediadigital/vibe-s3

No need ;-)
Just use the `aws s3` cli command  - it's officially from Amazon, reasonably fast (we are taking about transferring a text file), stable and easy to use.

> Agains Phobos / numpy / liblinear / fftw and others.

Ideally we would have benchmark tests for every method, s.t. we know what we have to tweak.
The output could look like this (simplified):

```
{
   "meta": {
       some info like `runTime`, `architecture`, `gitTag`, ...
   },
   "random":  {
      "binomial": [
          {"library": "mir", "time": 15.0},
          {"library": "numpy", "time": 20.0}
      ],
      "normal": {
         "small": [
              {"library": "mir", "time": 5.0},
              {"library": "numpy", "time": 10.0}
         }
     }
   }
}
```
- there might be multiple tests for a method 
- there might not always be an analog in the comparison libs
- you probably want every tests to be a single file, s.t. it's easier to run them individually

---

1) We use first a different repository to try out things - we don't mess up the git history (it might be tricky to get all the dependencies right) & we can still put it back to the main lib if we want to.

2) File structure

```
random/
     normal/
         mir.d
         numpy.d
         liblinear.c
         phobos.d
         tests/
            small.in
            small.out
            large.in
            large.out
```

3) If you are afraid of the IO overhead, the programs could emit a "TEST_START", and "TEST_END" on stderr, but imho the examples should be large to make this negligible.

4) Execution logic

It should be fairly easy then to write a small script reads such a file tree and executes each program. - - For every filename it can have a simple execution/building map (e.g. `phobos.d` -> [`dmd`], `mir.d` -> [`dmd`, `ldc`], `numpy.d` -> [`python`])
- Binaries should all be put into a separate build directory
- The executors runs the binary/scripts step by step
  - calls them with the input file on `stdin` and puts their output into the temporary build directory too
  - records time spent (probably the used CPU time too)
  - diff the output file witht the saved correct solution (might be that we need something more complex here in the future)
  - remove the output file
  - create the `json` file for the subfolder

5) Good examples

It might be hard to find good examples that actually take a lot of time to run and don't emit a lot of output on stdout, but maybe for the beginning we could trust that the program actually does N iterations of the same op - do you know a better approach here?

6) We should probably provide an `install.sh` that downloads all the required libraries and binaries once.

**Comment by 9il** [comment]
> No need ;-)
> Just use the aws s3 cli command - it's officially from Amazon, reasonably fast (we are taking about transferring a text file), stable and easy to use.

+1, vibe.d is very buggy

**Comment by wilzbach** [comment]
> It might be hard to find good examples that actually take a lot of time to run and don't emit a lot of output on stdout, but maybe for the beginning we could trust that the program actually does N iterations of the same op - do you know a better approach here?

I thought about this and probably we don't want that, but just a single iteration - maybe with the `START_TEST` tag, so that we don't count the io time.
The runner should then run each programs for X seconds and report the average and its standard deviation.

**Comment by wilzbach** [comment]
I just found an experiment from NASA that compares a couple of different languages (NumPy, Fortran, Matlab, Java)

https://modelingguru.nasa.gov/docs/DOC-1762

They only provide 3 tests, but maybe it's still worth to check whether such benchmarking already exists and we just need to adapt it for mir?

**Comment by wilzbach** [comment]
See also: http://eigen.tuxfamily.org/index.php?title=Benchmark

**Comment by 9il** [comment]
- Yes, new repository
- No executable files
- Each test should have shell script to execute it and get JSON.
- a program should test its execution time. Furthermore output data for program maybe a vector or tensor of values. For example FLOPS for dot product depending from vector size

**Comment by 9il** [comment]
> See also: http://eigen.tuxfamily.org/index.php?title=Benchmark

BTW, I don't believe in their tests. They are not fair. INTEL_MKL is faster or equal to openBLAS. They can not be faster for matrix x vector product, thought

**Comment by 9il** [comment]
> See also: http://eigen.tuxfamily.org/index.php?title=Benchmark
> BTW, I don't believe in their tests. They are not fair. INTEL_MKL is faster or equal to openBLAS. They can not be faster for matrix x vector product, thought

Maybe i am wrong)

**Comment by wilzbach** [comment]
> Each test should have shell script to execute it and get JSON.

Hmm it might be quite annoying to do the same thing all the time - the compiling, linking, and measuring of the execution, cleaning up are the same for every test. Hence the idea to have a small runner that handles that for you - it's also nicer, because you don't duplicate information.

I have done the same mistake before, e.g.

https://github.com/wilzbach/d-parsing-perf
https://github.com/wilzbach/bam-perf-test
...

So go for a global runner script - or at least a shared library that you can import ;-)
