### ISSUE TITLE
Name conflict(s)  with Ubuntu mir

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#188]
> That name will get you into trouble... While I would have no problem
> introducing it to Debian (name isn't taken), on Ubuntu, "mir" (along
> with "libmir" is the name of the MIR display server Canonical is
> developing in-house. There are a few ways to resolve the situation
> (easiest being "rename one of the projects"), but this will need to be
> investigated.
> This is an Ubuntu-only issue though, o Debian we could take the name
> mir, unless someone is planning to package the mir display server
> (which I guess won't happen soon).

Apart from the fact that we would need to have a different name for Ubuntu, there is also the aspect of branding - everyone should be able to connect a name uniquely to a project (e. g. I talked today on the #d irc about mir and was mistaken for the Ubuntu project). This also brings the problem of googling for solutions of the name is so overused. 

I just put this out here, so that we don't forget it. 
##

**Comment by 9il** [comment]
Does not look actual today. Mir Optim is only candidate fir Debian
