### ISSUE TITLE
allow upSize for sliced

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#19]
It would be quite nice to handle be able to fit an existing slice into an larger one (for `sliced`).
Have a look at this example from NumPy:

```
>>> b = np.array([[0, 1], [2, 3]])
>>> b.resize(2, 3) # new_shape parameter doesn't have to be a tuple
>>> b
array([[0, 1, 2],
       [3, 0, 0]])
```

I imagine sth. like this:

```
iota(4).sliced!Yes.allowUpsize(2, 3)
```

(but be aware of the flag "hell" - see #18)

**Comment by 9il** [comment]
This kind of functions may allocate. So they are for the future allocation module

**Comment by 9il** [comment]
This concept is not valied for ndslice. It may be replaced with concatenation or slicing.
