### ISSUE TITLE
expose isVector and isMatrix

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#193]
I think they are useful for users too, what is the best place to move them too?
##

**Comment by 9il** [comment]
We need more experience with slice, thought

**Comment by wilzbach** [comment]
Definitely, but only by exposing it to the user we might get feedback. I think in the worst case we have to redefine the template, but afaict it's pretty sure that those two methods will be needed?

**Comment by 9il** [comment]
This is not obvious for me

**Comment by wilzbach** [comment]
> This is not obvious for me

Okay then let's keep this open until we have more experience?

**Comment by 9il** [comment]
yes

**Comment by 9il** [comment]
isSlice return slice packs. So it can be used instead.
