### ISSUE TITLE
reshape should be nogc

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#2]
[came up after reading comment https://github.com/DlangScience/mir/issues/1#issuecomment-170299410]

I think sliced and reshape should be nogc, eg:
auto slice = 1000.iota.sliced([5, 6, 7], 9);
=> should be completely gc free.

The only think that comes to my mind is formatted error messages, for which https://github.com/DlangScience/mir/issues/1#issuecomment-170327051 provides a nogc solution [to be generalized to more than 1 integer to format, if need be]
##

**Comment by 9il** [comment]
Exceptions are GC stuff. They will be RefCounting in the future.

**Comment by 9il** [comment]
`assert` is `@nogc`

**Comment by 9il** [comment]
But `reshape` should always throw.

**Comment by timotheecour** [comment]
ok, so we agree on sliced being nogc? (pending https://github.com/DlangScience/mir/issues/1 to keep good error messages) 

for reshape, shouldn't it also assert instead of throw?
i think it should be same behavior as sliced: sliced asserts when dimensions mismatch, so why would reshape instead throw when dimensions mismatch?

advantage: more efficient in release mode.

Alternative (also allowing nogc), which is more fine grained than -release:

use:

version(D_NoBoundsChecks){
}
else{
  assert(somthing about indexes and dimensions, some formatted msg);
}

[D_NoBoundsChecks is passed with -noboundscheck]

**Comment by 9il** [comment]
> ok, so we agree on sliced being nogc? (pending #1 to keep good error messages)

Yes

> for reshape, shouldn't it also assert instead of throw?

Throw. `@nogc reshapeImpl` can be added in the future.

> reshape instead throw when dimensions mismatch?

ReshapeEx are thrown when it is impossible to reshape without reallocation. It is not obvious for a user.

**Comment by 9il** [comment]
BTW `sliced` already `@nogc`

**Comment by 9il** [comment]
Phobos is available now: https://github.com/dlang/phobos/pull/4930

**Comment by 9il** [comment]
fixed in mir-algorithm
