### ISSUE TITLE
opEquals for byElement

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#207]
shouldn't the following work?

```
int[] arr = [1, 2, 3, 4];
asert(arr.sliced(2, 2).byElement == arr);
```

**Comment by 9il** [comment]
Can be written with `.equals(arr)`. I should not add such rare cases thought. If we add this case, we need to add also `==` between 2 ByElement, which would be bad style because ByElement is hidden in the function.

**Comment by wilzbach** [comment]
> I should not add such rare cases thought. 

Fair enough - I was just surprised that it's not working.

>  which would be bad style because ByElement is hidden

why is it bad style to have opEquals for a Voldermort type?

**Comment by 9il** [comment]
> why is it bad style to have opEquals for a Voldermort type?

Because `==` would work with different types. One Voldermort type should know something magic about other Voldermort type.
