### ISSUE TITLE
DataFrames

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#208]
@DannyArends talked with me today, I pointed out that DataFrames are very useful in e.g R or pandas (python).

I just put here shortly my thoughts why people like it:
- column names, row indexes
- different types per column
- "sqlite"-like operations on table head, tail, sort, filter, group, join, ...
- row/column-wise functions
- easy import/export of the DataFrame from csv, hdf5, sqlite, excel, ...

See e.g. http://pandas.pydata.org/pandas-docs/stable/10min.html

It might not fit entirely in the context of mir, but I guess it's generally a huge userbase that we should keep in mind.
Maybe @DannyArends has more thoughts and experiences to share? ;-)
##

**Comment by 9il** [comment]
Has it standard?
Is it column based (in-memory representation)?

**Comment by jmh530** [comment]
@9il A pandas data frame is basically a numpy array with an index. Since a numpy array can be row or column oriented, I don't see a reason why you can't do both. However, I think most people use it in a column-order fashion.

**Comment by 9il** [comment]
no plan to add this package into the main mir repo
