### ISSUE TITLE
multi-dimensional folding 

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#209]
I just remembered that we wanted to allow reducing the dimensions by folding - so I put for here for our digital memory. 

Ideally the API allows to reuse common algorithms from std.algorithm.iteration/searching.

Numpy allows to specify an [axis](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.sum.html) parameter:

> Axis or axes along which a sum is performed. The default (axis = None) is perform a sum over all the dimensions of the input array. axis may be negative, in which case it counts from the last to the first axis.
> If this is a tuple of ints, a sum is performed on multiple axes, instead of a single axis or all the axes as before.

@9il if I rememberremember correctly, you wanted to use `pack` for this?

**Comment by 9il** [comment]
> @9il if I rememberremember correctly, you wanted to use pack for this?

Yes

**Comment by jmh530** [comment]
I find the documentation on pack quite confusing at the moment.

**Comment by 9il** [comment]
@jmh530 If you have time to improve it please make PR into Phobos. I am really not so good in writing docs

**Comment by jmh530** [comment]
@9il After thinking about it, the documentation isn't really the most unclear part. I think it's the example. Made it simpler here:
https://github.com/dlang/phobos/pull/4631

**Comment by 9il** [comment]
[`ndmap`](https://github.com/dlang/phobos/pull/4652) is significant step forward :-)
BTW, @jmh530 please refer comment in the your PR. I think it is really important for users and should be merged

**Comment by jmh530** [comment]
Will try to fix it tomorrow.

**Comment by 9il** [comment]
Fixed with #270
