### ISSUE TITLE
ndslice.algorithm

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#212]
https://github.com/dlang/phobos/pull/4652

**Comment by wilzbach** [comment]
We had the discussion of this algorithm package [already](https://github.com/libmir/mir/issues/50) - can I put the [NumPy sortng,searching and counting](https://github.com/libmir/mir/wiki/NumPy:-Sorting,-searching,-and-counting) algorithms for the multi-dimensional case on the list too?

**Comment by 9il** [comment]
Yes, but don't copy past this list and propose D API version instead. 

## Folding

`foldSlice`, `accSlice` should be ok, we don't need something like `maxElem`, and `minElem`, thought. 

## Searching

Searching API is more interesting part.

## Sorting

Sorting can be performed using std.algorithm: `slice.byElement.sort` and I have not idea how this can be optimized.

**Comment by 9il** [comment]
Also we probably need to update the wiki with examples or remove it. If a user will read this wiki he would think that ndslice and Mir is useless.

**Comment by 9il** [comment]
Fixed in #270 . Sorting examples will be added in the future
