### ISSUE TITLE
Performance issue with difference indexing syntax

### ISSUE THREAD

**Issue by dextorious** [9il/dip80-ndslice#215]
It appears that indexing on slices as A[i][j] is considerably faster than A[i,j] in at least some cases. To illustrate, here is a minimal example with three implementations of a simple finite difference calculation (simulating the 2D diffusion equation on a regular grid with a basic FTCS scheme):
https://dpaste.dzfl.pl/dfed4c6f7409

To reproduce, uncomment each implementation example in turn and time the execution. On my machine, using LDC 0.17.1 via "ldmd2 -release -inline -boundscheck=off -O test.d" on XUbuntu 16.04 and the latest Mir available on dub, the timings (obtained through the standard *nix time utility and averaged over a few runs) are as follows:

Implementation 1 ([i][j]): 1.597s
Implementation 2 ([i,j]):  1.818s
Implementation 3:          1.816s

The difference confused me and I couldn't find any reason for it in the existing documentation, so after asking on IRC I was directed to make an issue here. Please note that I'm very new to the language and it's entirely possible that some silly oversight on my part is at fault here.
##

**Comment by 9il** [comment]
This is not D or Mir issue. For me this does not look like an issue at all.

The first example works faster because compiler can move `f[i]` out of the inner loop.
If you change

```
        foreach (i; 1..f.length!0-1)
        foreach (j; 1..f.length!1-1)
```

to

```
        foreach (j; 1..f.length!1-1)
        foreach (i; 1..f.length!0-1)
```

compiler would not be able to do this optimization an the perfomance would be approximately the same like in the second variant (if all `f` located in CPU cache).

**Comment by dextorious** [comment]
I see. Without much understanding of how ndslice works internally, I had assumed that the same transformation was also possible in the f[i,j] case. With only knowing what the available documentation says, it is difficult to appreciate the actual difference between f[i][j] and f[i,j].

This also represents a fairly general constraint on how optimal implementations of a very wide class of stencil algorithms should be written in D/Mir and, sadly, makes the rather elegant sliding window construction unsuitable for calculations such as this (unless I'm missing something). Perhaps this could be illustrated in future documentation, as I suspect I may not be the only newcomer to fall into this trap.

**Comment by 9il** [comment]
Sliding windows works well for medium and big windows sizes, 20x20, 100x100.

Diffusion calculations should be optimized more (with SIMD instrucitons) and can be part of a of the Mir library, thought.

You are welcome to update docs at Phobos / Mir. Also an overview of diffusion algorithms would be very helpful.

**Comment by dextorious** [comment]
Diffusion calculations are a small subset of general stencil operations common to all finite difference approximations (which almost always feature small windows, usually up to 5x5). I picked that as a simple example to see what performance I could get before writing some more general scientific code.

Regarding SIMD, does core.simd still represent the recommended approach to writing SIMD code in D? I'd be happy to try to further optimize my example with the aim to eventually include it in the documentation as part of something like a general overview of best practices / gotchas to writing performant numerical code with Mir for newcomers like me. 

And if there's interest in including implementations of common simple algorithms like diffusion stencils or finite difference approximations in the library, I'd happily contribute there too. I have far more experience writing generic numerical code (mostly in C, Python and Julia) than in writing D, so it seems like a good place to start.

**Comment by 9il** [comment]
> Regarding SIMD, does core.simd still represent the recommended approach to writing SIMD code in D?

`core.simd` is useless.

> I'd be happy to try to further optimize my example with the aim to eventually include it in the documentation as part of something like a general overview of best practices / gotchas to writing performant numerical code with Mir for newcomers like me.

Generally we don't need to use any SIMD opcodes. 90% of work is data/instruction rearrangement:
http://web.cs.ucla.edu/~pouchet/doc/ics-article.13.pdf
or
http://repository.cmu.edu/cgi/viewcontent.cgi?article=1263&context=ece

so compiler can use loop or SLP vectorization.

> And if there's interest in including implementations of common simple algorithms like diffusion stencils or finite difference approximations in the library, I'd happily contribute there too. I have far more experience writing generic numerical code (mostly in C, Python and Julia) than in writing D, so it seems like a good place to start.

Don't worry about generic or low level optimizations. If you can contribute good algorithms, then we can improve generic abstractions and code optimizations together.
