### ISSUE TITLE
More convenient Iota wrapper

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#22]
Looking throw the unittests I see this pattern coming up > 80% of all tests.

```
auto b = 4.iota.sliced(2, 2);
auto tensor = 60.iota.array.sliced(3, 4, 5);
auto a = 240000.iota.sliced(10, 20, 30, 40);
```

I do like this pattern, but seeing 1) how often this occurs and 2) that you need to know the size of iota no that `downSize` is disabled by default it seems to me that having a convenience wrapper for this, like `Iota`.

```
Iota.sliced(10, 20, 30, 40);
```

It looks nicer and avoids the problem that you actually mistyped the number of elements - which can only be evaluated in runtime - e.g. `24000.iota.sliced(10, 20, 30, 40);` will result in an hard-to-see runtime error.

I haven't thought much about how we could combine this `start, stepsize` from usual iota, but how about:

```
Iota!10(10,20,30,40) // starts at ten
Iota!(10, 2)(10,20,30,40) // starts at ten, with steps of 2
Iota!(10, 0.5)(10,20,30,40) // starts at ten, with steps of 0.5
```

Would be happy to send a PR for this ;-)

**Comment by 9il** [comment]
No allocations, but the same logic (compute total length from dimensions). So this is for the future allocation module too

**Comment by wilzbach** [comment]
@9il Let me know your progress on the future allocation module and how I can help you moving this amazing library forward ;-)

**Comment by 9il** [comment]
@greenify If you would have a time to improve documentation or write an article for Numpy users (with compression like in #24) this would be really helpful!

**Comment by wilzbach** [comment]
Sure I will do that, but I was more asking for coding tasks ;-)

**Comment by wilzbach** [comment]
@9il I copied all function headers from NumPy into the [wiki](https://github.com/DlangScience/mir/wiki/NumPy), so we can start by tagging
- what is implemented and how it can be achieved with `mir`
- what is in process (just rough areas, e.g. I think you already have a stats module)

**Comment by wilzbach** [comment]
@9il as `squeeze` didn't turn out that well, what other functions/feature do you want to bring to mir in the future?

Imho [Array creation](https://github.com/DlangScience/mir/wiki/NumPy:-Array-creation), [Array manipulation](https://github.com/DlangScience/mir/wiki/NumPy:-Array-manipulation-routines) 
and [Ndarray](https://github.com/DlangScience/mir/wiki/NumPy:-Ndarray) build a lot of the "basics" in NumPy, but this is just my opinion.

Let me know how to help best ;-)
