### ISSUE TITLE
Convenient aliases: `T` and `I`

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#23]
Coming from NumPy I would propose to reserve the following two short aliases:
- `T` as a property alias for `transposed`
- `I` as a property alias for `inverted`

This is often quite handy

**Comment by wilzbach** [comment]
@9il what do you think about these convenience aliases?

**Comment by 9il** [comment]
We can think about it when we implement LAPACK from scratch for matrix inversion XDD

**Comment by 9il** [comment]
We don't use them as public global names. So they are available

**Comment by wilzbach** [comment]
> We don't use them as public global names. So they are available

Great! Then I would propose to add them - it's also useful without lapack and it's purely an api question ;-)

**Comment by 9il** [comment]
Would not be path of the Phobos. This may be implemented in the script like shell over the Mir library
