### ISSUE TITLE
Discrete distribution sampling in O(1) using Alias or Marsaglia method

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#237]
Both the [Alias method](https://en.wikipedia.org/wiki/Alias_method) and [Marsaglia method](https://www.jstatsoft.org/article/view/v011i03) allow to sample from a discrete distribution in O(1).

(related to #233)

**Comment by 9il** [comment]
yep, Discrete should be renamed to `NaiveDiscrete` thought. And Alias method should be added.
