### ISSUE TITLE
Swap axis

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#24]
I am still looking at NumPy and ndslice ;-)
Here's something nice that is still missing.

Interchange two axes of an array.

I know there is `everted` that changes entirely the order of the axes, but
sometimes it is useful just to switch to specific ones.

```
>>> np.swapaxes(x,0,2)
array([[[0, 4],
        [2, 6]],
       [[1, 5],
        [3, 7]]])
```

https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.swapaxes.html

**Comment by 9il** [comment]
This is already implemented: `x.swapped!(0, 2)` or  `x.swapped(0, 2)`
