### ISSUE TITLE
mir.random.ars - adaptive rejection sampling

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#247]
I came across ARS (adapative rejection sampling) quite often lately. In contrast to #240 (Flex algorithm), there is _no_ setup phase and the intervals are split only when `X` is rejected.
- [Original paper by Gilks](http://www.math.chalmers.se/Stat/Grundutb/CTH/mve186/1415/adaptive.sampling.pdf)
- [Summary presentation](http://www2.stat.duke.edu/~cnk/Links/slides.pdf)
- [Wikipedia](https://en.wikipedia.org/wiki/Rejection_sampling#Adaptive_rejection_sampling)
- [R package ARS](https://cran.r-project.org/web/packages/ars/ars.pdf)
- [Improved Adaptive Rejection Metropolis
  Sampling Algorithms](https://arxiv.org/pdf/1205.5494.pdf)
- [Python implementation](https://github.com/alumbreras/ARS/blob/master/ars.py)

It's advantage:

> On average only three evaluations of the log density are required to accept one point, provided good initial points are chosen.

However for ARS
- density **must be log-concave**
- inflection points need to be known a priori
- variation exists: "derivative-free ARS" (doesn't require derivatives nor continuous functions, but requires more evaluations - on average five)

Ping @WebDrake @joseph-wakeling-sociomantic.

I don't think that implementing ARS is worth the effort, because
1) if a user needs zero startup costs, he can simply hard-code the FlexIntervals
2) ARS doesn't solve the problem of being able to sample from any distribution, on the contrary it requires even more assumptions (log-concave!)
3) I don't believe that low memory requirements are a key factor, but even if a higher `rho` with the Flex algorithm will yield less intervals.

**Comment by joseph-wakeling-sociomantic** [comment]
@wilzbach just took a glance through the paper.  I agree that it's probably not worth implementing a technique more than 20 years old with less flexibility, though it's interesting to see.

BTW, I noticed that almost all these papers wind up citing Devroye's 1986 book _Non-Uniform Random Variate Generation_; this is freely available online if you're interested: http://luc.devroye.org/rnbookindex.html

**Comment by wilzbach** [comment]
> @wilzbach just took a glance through the paper. I agree that it's probably not worth implementing a technique more than 20 years old with less flexibility, though it's interesting to see.

thanks for the feedback, Joe :)

> BTW, I noticed that almost all these papers wind up citing Devroye's 1986 book Non-Uniform Random Variate Generation; this is freely available online if you're interested:

Yep noticed that too, a copy is also in our [shared paper folder](https://drive.google.com/drive/folders/0BwdiZp7qSaBhakl6d2hCVjRfdXc).

Another particularly interesting book from the familiar authors of Tinflex (Hörmann, Leydold) is 
**"Automatic Nonuniform Random Variate Generation"**.
