### ISSUE TITLE
Docs should have versioning

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#252]
##

**Comment by wilzbach** [comment]
It's very easy to just dump them into a folder, but there are two problems:

1) Show a notice on outdated docs to switch to the latest version
a) we could use a bit of JS to show such a warning if the URL doesn't contain `latest`
b) we could write the latest version to a file, load it via XHR and then show the warning - not ideal either

2) Showing a select box which allows the user to switch between versions. We could potentially use sth. like `git tag | tail -n 10` - I will look into this soon.

**Comment by 9il** [comment]
wontfix in near future
