### ISSUE TITLE
Appveyor can be simplified

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#253]
Appveyor allows to chose platform: x86 x86_64 or both. See preferences
##

**Comment by wilzbach** [comment]
I know, but IIRC it didn't work with the build matrix.
Moreover for example we don't test ldc with 32bit on Windows atm.

In general I would like to reduce the complexity of the AppVeyor build script, but I don't have a Windows machine, so it's difficult to test changes.

**Comment by 9il** [comment]
Yep, we have enough todo. This is just reminder.
