### ISSUE TITLE
SDL is buggy for DUB

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#258]
... so we need to change it to JSON. For example, `"dflags-ldc": ["-mcpu=native"]` SDL analog seems broken

**Comment by wilzbach** [comment]
> For example, "dflags-ldc": ["-mcpu=native"] SDL analog

What did you try?

It should be something like `dflags-ldc: "-mcpu=native"`

But are you sure `dflags-ldc` exists? A [search](https://github.com/dlang/dub/search?utf8=%E2%9C%93&q=dflags-ldc) at the Dub repo didn't find it.

**Comment by 9il** [comment]
it exists for json, but not for sdl

**Comment by 9il** [comment]
`dflags-ldc "-mcpu=native"` does not work

**Comment by s-ludwig** [comment]
Just stumbled over this - the eqiuvalent is `dflags "-mcpu=native" platform="ldc"`. See also http://code.dlang.org/package-format?lang=sdl#platform-specs

**Comment by 9il** [comment]
@s-ludwig Thank you, my bad
