### ISSUE TITLE
fromArray

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#26]
It would be nice to have a way to convert a multi-dimensional array to a slice, e.g.

```
[[1,2], [3, 4]].fromArray
```

**Comment by John-Colvin** [comment]
It's a bit expensive to traverse all the arrays to check that it's square. Not that we shouldn't have such a function, but it is a cost to consider.

**Comment by 9il** [comment]
added `shape` for ndarrays, see also its unittests #38

**Comment by 9il** [comment]
fixed with #38
