### ISSUE TITLE
merging back into phobos

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#28]
Just out of interest how you plan to accomplish

> mir.ndslice is a development version of the std.experimental.ndslice package.

At least with the changed paths it sounds like a lot of work to get new commits from here to phobos without messing up the history ...

**Comment by 9il** [comment]
I just open PR to Phobos after mir. We can work on a new module during a month at mir and then push it to Phobos with single commit.

**Comment by 9il** [comment]
I already have advanced summation algorithms for ndslice. Hope to share it next week

**Comment by wilzbach** [comment]
> I just open PR to Phobos after mir.

Ah I was worried about that changing module paths `mir.ndslice` -> `std.experimental.ndslice` might mess up the history.

> We can work on a new module during a month at mir and then push it to Phobos with single commit.

Sounds nice! I like this policy :)

**Comment by wilzbach** [comment]
>  We can work on a new module during a month at mir and then push it to Phobos with single commit.

There are two issues that I discovered that might be problematic:

1) Handling bugfixes could be tricky (a PR has to made to both Phobos and mir)
2) The Phobos repository will not contain a proper commit history - so it might be difficult for them to review changes (especially if they are large). Currently they merge it because they [trust you] :)(https://github.com/D-Programming-Language/phobos/pull/3940) (@quickfur)

**Comment by 9il** [comment]
> 1) Handling bugfixes could be tricky (a PR has to made to both Phobos and mir)

Yes, however this would help users to go with recent changes.

> 2) The Phobos repository will not contain a proper commit history - so it might be difficult for them to review changes (especially if they are large). Currently they merge it because they [trust you] :)(D-Programming-Language/phobos#3940) (@quickfur)

Phobos will contain proper commit history. It should not contain dev. commits, but  release commits and bug fixes.

**Comment by 9il** [comment]
@greenify BTW, have you read my letter with small overview of your GSoC plan?
