### ISSUE TITLE
Add dynamically linked libraries to AUR package

### ISSUE THREAD

**Issue by WebFreak001** [9il/dip80-ndslice#280]
People can then depend on libmir and compile their program dynamically without worrying about increased file size too much. Then nobody needs to have the same libmir 20x on their computer because every program ships their own version or statically links to it.
##

**Comment by wilzbach** [comment]
@WebFreak001 thanks for you feedback. I will try to address it:

1) A lot of mir is templated, s.t. using a dynamic library doesn't help you much (look at the size of the executeables, for `means_of_columns` it's 1803.4K with static linking and 1805.1K for dynamic linking)
2) Mir is still under heavy development, so you do want to compile it into your program to avoid potential versions problems
3) Building libraries in a common way is still a mess with dub (e.g. https://github.com/dlang/dub/issues/838), which means it won't pickup the globally installed version.
4) You currently need the latest ldc version (e.g. `ldc-git`)
5) I am not sure whether we can compile a library with `dmd` and then use it with other compilers?
6) I have updated both AUR packages to include static and dynamic libraries. Please let me know any feedback you have (I am still a young AUR packager).
7) I think the libraries need to be build with all optimizations levels, but then you would loose all the nice debug output. @WebFreak001 @9il what's the typical way to handle this?

It should behave in the following way:

## Static linking

```
dmd means_of_columns.d /usr/lib/libmir.a
```

## Dynamic

```
dmd means_of_columns.d -L/usr/lib/libmir.so
```

Do you know why directly using `-Llibmir.so` doesn't work on Arch?

Btw with `rdmd` it should work out of the box `rdmd means_of_columns.d`
(You can find the example `means_of_columns.d` here:  https://github.com/libmir/mir/tree/master/examples)

**Comment by 9il** [comment]
no plan to support packages without precompiled betterC API
