### ISSUE TITLE
Boundary condition with ndslice.selection.windows

### ISSUE THREAD

**Issue by ljubobratovicrelja** [9il/dip80-ndslice#291]
I see that ndslice.selection.windows is a very powerful concept, that can be utilized for image convolution (as you've shown in median filtering example), but I haven't found an easy way to include [boundary condition testing](https://en.wikipedia.org/wiki/Kernel_%28image_processing%29#Edge_Handling), so that image edges can be processed as well.

Can this be performed somehow? If not, was there any thought on how to implement this?
##

**Comment by 9il** [comment]
> Can this be performed somehow?

The are three options:
- Extend image with fat enough borders (requires reallocation)
- Construct lazy concatenation (requires the future ndslice.concatenation)
- Process edge cases separately. Different approaches  can be used for different filters. For example median will work well with truncated windows. But matrix filters requires full window, so border reflection (or gray color or something else) and temporary window can be used.

The first variant is fast for images if they can feet to cache, but it may significantly slowdown if not.
The second variant will slowdown filters because complex indexing.
The third one is the fastest, but requires more efforts. Generic version may be added in the future. But i want to see real world usage first

**Comment by ljubobratovicrelja** [comment]
I'd say for image processing purposes that first variant is not a valid option. Maybe caching could be used for some applications, but in research work this wouldn't make much sense.
I'm not sure to what are you referring to in second - I'm not familiar yet with ndslice.contatenation, I'll inspect it to try to see what you mean.
The third option is not an "easy" variant. :) It is obviously a way to handle it, but I was hoping for a bit more elegant way.

> Generic version may be added in the future. But i want to see real world usage first

Well, you've shown a real world usage with median filtering! Any form of image convolution would imply border handing of some sort, as is shown in all mayor image processing toolkits ([matlab's conv](http://www.mathworks.com/help/matlab/ref/conv.html?requestedDomain=www.mathworks.com) has _shape_ parameter, [OpenCV's filter2D](http://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html#filter2d) has borderType parameter, and  of course [DCV's conv](https://github.com/ljubobratovicrelja/dcv/blob/master/source/dcv/imgproc/convolution.d#L65-L83) has bc template parameter). Sorry if I'm stating the obvious here, are you thinking of something else by _real world example_?

**Comment by 9il** [comment]
> I'm not sure to what are you referring to in second - I'm not familiar yet with ndslice.contatenation, I'll inspect it to try to see what you mean.

It is not ready for now)

**Comment by 9il** [comment]
> Well, you've shown a real world usage with median filtering! Any form of image convolution would imply border handing of some sort, as is shown in all mayor image processing toolkits (matlab's conv has shape parameter, OpenCV's filter2D has borderType parameter, and of course DCV's conv has bc template parameter). Sorry if I'm stating the obvious here, are you thinking of something else by real world example?

No, I just need more time/examples to be sure that my imagination of an API and algorithm ideas is good enough to write it down to Mir.

**Comment by ljubobratovicrelja** [comment]
> It is not ready for now)

OK, no worries - I'll monitor its progress anyways.

> No, I just need more time/examples to be sure that my imagination of an API and algorithm ideas is good enough to write it down to Mir.

I understand, good strategy. I'll keep on thinking about this, and let you know if I come up with any firm solution. I'd really like to see this work, it would be a killer feature for image processing!

**Comment by 9il** [comment]
no in the plan for now
