### ISSUE TITLE
[Tinflex] recycle the uniform random variable from discrete sampler

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#299]
The Tinflex paper recommends to recycle the uniform random variable generated for picking an interval according to the hatArea probs (in our case the discrete distribution sampler).

This is just here to figure out whether it makes a difference (in terms of overall speed) and is worth it (= no loss in the quality of the distribution)
##

**Comment by 9il** [comment]
please reopen in mir-random if actual
