### ISSUE TITLE
[Tinflex] send approximations PRs

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#300]
(for `area` and `flexImpl`)
##

**Comment by 9il** [comment]
you may want tinflex label

**Comment by wilzbach** [comment]
> you may want tinflex label

I thought the "random" label (which I created), is more generic and combined with the prefix annotation it's clear to everyone as labels aren't shown in email notifications?

**Comment by 9il** [comment]
~~Does not help :-(~~ wrong thread

**Comment by 9il** [comment]
please reopen in mir-random if actual
