### ISSUE TITLE
Bad docs stile

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#306]
The spaces between strings are too large
http://docs.mir.dlang.io/latest/mir_glas.html

**Comment by 9il** [comment]
@wilzbach do you have any idea about what this bug?

**Comment by wilzbach** [comment]
Not really, but I have a guess (probably some weird things of ddoc which can probably be fixed by removing the <br>s from the ddoc style sheet)

**Comment by 9il** [comment]
Does not help :-(

**Comment by 9il** [comment]
Partially fixed with #315

**Comment by 9il** [comment]
fixed now :)
