### ISSUE TITLE
Radial basis function

### ISSUE THREAD

**Issue by ljubobratovicrelja** [9il/dip80-ndslice#308]
Since support vector machine is mentioned in past, I suppose radial basis function network would also be useful feature to have in Mir?

If you agree, I could implement most basic network model. If there is anyone more experienced in this field, I'd be glad to pass the torch, but until that someone is found, I suppose it'd be nice to have most basic implementation that works. How does that sound to you guys?
##

**Comment by 9il** [comment]
LGTM. We can put it to experimental until someone will give us full overview. Please try to keep API simple and low level

**Comment by ljubobratovicrelja** [comment]
> We can put it to experimental until someone will give us full overview

I agree.

> Please try to keep API simple and low level

Will do.

**Comment by ljubobratovicrelja** [comment]
Hey guys!

I've put up a RBF development repo [here](https://github.com/ljubobratovicrelja/mir.experimental.model.rbf). I did this to make the development and debugging easier for me - once I'm happy with it, I'll put it on my Mir fork, and make a PR.

For the first version, I'd like to implement global ridge regression method with manually assigned regularization parameter. It performs quite well, and it's easy to implement. I'll be following [this tutorial for implementation](http://www.cc.gatech.edu/~isbell/tutorials/rbf-intro.pdf), since it sums up nicely all details presented in papers on this topic. For now I have implemented most basic version in my repo, but API is still far from what I'd present to you.

Also, important reason I've decided to make a temporary repo is that I'm missing matrix inversion in Mir, so I'm using scid's. I suppose inversion is coming up in glas? If yes, is there an ETA?

**Comment by 9il** [comment]
> I've put up a RBF development repo here. I did this to make the development and debugging easier for me - once I'm happy with it, I'll put it on my Mir fork, and make a PR.

Great!

> Also, important reason I've decided to make a temporary repo is that I'm missing matrix inversion in Mir, so I'm using scid's. I suppose inversion is coming up in glas? If yes, is there an ETA?

1-2 months.

**Comment by ljubobratovicrelja** [comment]
> 1-2 months.

Cool, tnx!

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo

**Comment by 9il** [comment]
> 1-2 months.
> 
> Cool, tnx!

Lubeck contains inversion

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
