### ISSUE TITLE
Ability to pad slices

### ISSUE THREAD

**Issue by henrygouk** [9il/dip80-ndslice#311]
The ability to pad slices could come in handy for image processing operations, among other things.

Something with similar behaviour to MATLAB's padarray function is what I am thinking of.
##

**Comment by henrygouk** [comment]
A solution to this would also solve #291

**Comment by 9il** [comment]
Thanks!

**Comment by henrygouk** [comment]
It should be possible to implement this in a way that performs the padding lazily as elements are accessed, which would be nice in the sense that allocations wouldn't be needed. This would obviously increase the number of instructions required to access elements in the padded slice, but that problem can be somewhat mitigated by calling the `slice` function to allocate a new slice that has the padding eagerly evaluated.

**Comment by 9il** [comment]
@henrygouk [stack](http://docs.algorithm.dlang.io/latest/mir_ndslice_stack.html#.stack) function was added . In combination with `repeat` from `ndslice.topology` it allows to create padding view and allocate new image with `slice`. `Stack` does not have `[...]` access primitives.

**Comment by 9il** [comment]
> It should be possible to implement this in a way that performs the padding lazily as elements are accessed, which would be nice in the sense that allocations wouldn't be needed. This would obviously increase the number of instructions required to access elements in the padded slice, but that problem can be somewhat mitigated by calling the slice function to allocate a new slice that has the padding eagerly evaluated.

Lazy ndslice view for `stack` can be achieved using `mir.ndslice.topology.indexed` and `ndiota`.
See https://github.com/libmir/mir-algorithm/pull/29

I will reopen this Issue for mir-cv.

**Comment by 9il** [comment]
constant padding was added https://github.com/libmir/mir-algorithm/pull/31

**Comment by 9il** [comment]
edge, symmetric and wrap paddings https://github.com/libmir/mir-algorithm/pull/32
