### ISSUE TITLE
documentation build

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#32]
I guess in the near future we want to provide a generated online documentation, preferable automatically (e.g. travis build uploaded to s3).

Maybe Adam's new documentation [generator](http://dpldocs.info/experimental-docs/std.algorithm.html) is worth looking at.

**Comment by 9il** [comment]
> Maybe Adam's new documentation generator is worth looking at.

Have you build something with Adam's docs?

**Comment by wilzbach** [comment]
Nope, was just an idea. However I have done this Travis to s3 many times, so if you have a favorite doc generator, I would be happy to hack something together next week.

**Comment by 9il** [comment]
> Nope, was just an idea. However I have done this Travis to s3 many times, so if you have a favorite doc generator, I would be happy to hack something together next week.

I like https://github.com/kiith-sa/harbored-mod and Adam's doc engine looks good too. Mir requires all DDOC macros from Phobos. This will add some problems.

**Comment by wilzbach** [comment]
> Mir requires all DDOC macros from Phobos. This will add some problems.

Hmm yeah this is going to be tricky, but maybe taking the macro definition from the dlang.org repo is already enough. 

I am more worried about references to Phobos modules, so when using REF the link won't resolve, but perhaps as a workaround a simple regex could find these occurrences

An alternative would be to use the setup from dlang.org, but modified to only build Mir. 
The advantages here is that we avoid ui bugs due to different documentation engines if a module will be merged to Phobos and their css design is pretty sweet.

**Comment by wilzbach** [comment]
as `bootDoc` is working again - do you want to add that back to the Readme?

Btw should we archive every documentation version? We could just execute the `s3 copy` command to the `git describe --abbrev=0 --tags` (latest tag) too, but then we should probably provide a nice way for the user to switch between documentations and at the moment we didn't introduce any breaking changes  - so just an idea once the first official version is released.

**Comment by 9il** [comment]
> as bootDoc is working again - do you want to add that back to the Readme?

We still need to add macros like LREF and others.

**Comment by 9il** [comment]
> Btw should we archive every documentation version? We could just execute the s3 copy command to the git describe --abbrev=0 --tags (latest tag) too, but then we should probably provide a nice way for the user to switch between documentations and at the moment we didn't introduce any breaking changes - so just an idea once the first official version is released.

This would be helpful

**Comment by wilzbach** [comment]
After testing ddox, bootDoc, harbored-mod I gave@adamdruppe's new [adrdox](https://github.com/adamdruppe/adrdox/) a try:
http://docs.mir.dlang.io/adrdox/mir.combinatorics.html

It's still in an experimental stage, but I really like the fact how easy it is to give it a custom skeleton :)

**Comment by 9il** [comment]
Looks good

**Comment by wilzbach** [comment]
> I like https://github.com/kiith-sa/harbored-mod and Adam's doc engine looks good too

Seems like harbored is working again.
I gave it a try too: http://docs.mir.dlang.io/harbored/

**Comment by 9il** [comment]
Fixed with #203
