### ISSUE TITLE
non-uniform indexing [matlab,python]: iota(2*4).sliced(2,4)[0,[1,2,1]] (has sample code)

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#321]
matlab and python/numpy allow indexed operations such as:

```
a = np.arange(6).reshape((3, 2))
array([[0, 1], [2, 3], [4, 5]])

a[[1,2,1],:]
array([[2, 3], [4, 5], [2, 3]])
```

I couldn't find the equivalent in mir.

Possible notations:
- The indexing operation could either allocate or not

```
auto s= iota(2*4).sliced(2,4);

auto s2=s.indexed([1,1,2], ); // lazy computed elements
auto s3=s2.array; // allocates
```

More generally, `Slice:indexed(T...)(T ): T[i]` for each dimension i can be a scalar or an arbitrary range of integral indexes. 

Not sure whether `s.indexed(...)` should directly allocate or whether it'd be as efficient to allocate upon calling explicitly `s.indexed(....).array`

Eg use case:

filter out rows or columns with any NaN in them (obviously lots of use cases)
##

**Comment by 9il** [comment]
http://dlang.org/phobos/std_range.html#.indexed allows to index top dimension. Is it good for you?

**Comment by 9il** [comment]
btw, there is `http://docs.mir.dlang.io/latest/mir_ndslice_selection.html#iotaSlice`, it is faster then `iota(...).sliced(...)`

**Comment by timotheecour** [comment]
thanks for the link, only top dimension is too restrictive.

How about:

```
auto indexed(size_t N, Range, Indexes...)(auto ref Slice!(N, Range) a, Indexes indexes){
  size_t[N]shape;
  static assert(indexes.length==N);
  foreach (i; Iota!(N)){
    shape[i]=indexes[i].length;
  }

  alias T=typeof(a.byElement[0]);
  import std.algorithm:fold;
  auto count=shape.fold!`a*b`;
  import std.array:uninitializedArray;
  auto vals = uninitializedArray!(T[])(count);
  auto ret=vals.sliced(shape);

  import std.algorithm;

  auto ind=cartesianProduct(indexes);
  size_t i;
  foreach(indi;ind){
    // TODO:something simpler
    size_t[N]indi2;
    foreach (j; Iota!(N)){
      indi2[j]=indi[j];
    }
    auto val=a[indi2];
    //auto val=a[indi]; //CT Error

    vals[i]=val;
    i++;
  }
  return ret;
}

void test(){
  import std.stdio;
  auto s=iotaSlice(4, 5).slice;
  auto s2=s.indexed([1,1,2],[1,2]);
  assert(s2==[[6, 7], [6, 7], [11, 12]]);
}
```

tested and it worked; but not sure whether could be more efficient.

Also, is there a better way to do what i wrote above [see: TODO:something simpler]

**Comment by 9il** [comment]
Will be added in the new `concatenation` module. But we need another name, because operation is not lazy (wee need allocate indexes)

**Comment by 9il** [comment]
In addition, it should be 2 versions: 1 one with index allocation, another one with deep allocation.

**Comment by timotheecour** [comment]
- Not sure this belongs in `concatenation` (there's really no concatenation here...)
  maybe instead allocation ? (both concatenation and indexing as defined above do allocate)
- what do you mean by `index allocation` ? the only allocation is value allocation, happening here:   `auto vals = uninitializedArray!(T[])(count);`
- this function could optionally get a buffer as input (ie no alloc)

**Comment by 9il** [comment]
> Not sure this belongs in concatenation (there's really no concatenation here...)
> maybe instead allocation ? (both concatenation and indexing as defined above do allocate)

Maybe, i don't know for now

> what do you mean by index allocation ? the only allocation is value allocation, happening here: auto vals = uninitializedArray!(T[])(count);

`vals` is array of slices. So, it is some kind of index. The type of `ret` is `Slice!(M, Slice!(N, Range)*)` and it can not be unpacked.

**Comment by timotheecour** [comment]
Not sure what you mean? `vals` is an array of values (potentially floating point), not indexes;

Also, just checked that:

```
auto s2=s.indexed([1,1,2],[1,2]);
static assert(is(typeof(s2) == Slice!(2LU, ulong*)));
```

**Comment by 9il** [comment]
oh, my bad

**Comment by 9il** [comment]
```d
```

**Comment by 9il** [comment]
Solved: http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.indexed
