### ISSUE TITLE
Main package must have a binary target type, not sourceLibrary. Cannot build.

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#323]
How to build latest version of mir?

```
dub fetch mir
cd ~/.dub/packages/mir-0.15.3/mir
dub build --config=static-lib
#works
```

```
dub fetch mir --version=0.17.0-alpha2
cd ~/.dub/packages/mir-0.17.0-alpha2/mir
dub build --config=???
#doesn't work
```

**Comment by timotheecour** [comment]
after git clone https://github.com/libmir/mir/issues/323, replacing 
    "targetType": "sourceLibrary",
by
    "targetType": "library",
and typing dub build works

**Comment by 9il** [comment]
99% of source code is templates. Building Mir will just produce `ModuleInfo`. `dub test mir` should work anyway. Why you need to build it?

**Comment by timotheecour** [comment]
Well otherwise I get:
undefined reference to `_D3mir4glas2l312__ModuleInfoZ'

it works with pragma(lib, "mir") and proper -L-L flags

if it's <100%, why not allow building it?

unless you have a better way?

(PS: i'd like to use mir in an application that's not necessarily built via dub; it all works so long i can have a libmir that's built)

**Comment by 9il** [comment]
OK will add it back soon

**Comment by 9il** [comment]
For 0.17.0-alpha3: `dub build --config=static`

**Comment by wilzbach** [comment]
FWIW those targets are also needed for the ArchLinux packages
