### ISSUE TITLE
gemm,symm: Conjugated parameters seem redundant

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#326]
as the note shows ("GLAS does not require transposition parameters. Use mir.ndslice.iteration.transposed to perform zero cost Slice transposition."), why not just get rid of Conjugated?  (ie better to have only 1 obvious way to do something, assuming it's not more costly)

Unless it's for the case of complex conjugate numbers?

**Comment by timotheecour** [comment]
oh, looks like it's indeed for complex conjugate, nevermind

**Comment by 9il** [comment]
Do not forget, that for benchmarks you need to use LDC for your project: `dub build --compiler=ldmd2 --build=release`
