### ISSUE TITLE
lazy_tensor.slice => lazy_tensor.dup (slice is overloaded and doesn't convey allocation)

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#331]
Not to bikeshed, but I find this overload confusing:
http://docs.mir.dlang.io/latest/mir_ndslice_slice.html#.slice

```
auto slice(Flag!"replaceArrayWithPointer" replaceArrayWithPointer = Yes.replaceArrayWithPointer, size_t N, Range)(auto ref Slice!(N, Range) slice);

// creates duplicate using `slice`
auto dup = tensor.slice;
```

slice usually implies slicing of data (ie internal slice, no allocation or dupping).
what about instead `dup` which does convey allocation:

```
auto dup = tensor.dup;
// eg: 
auto tensor2=iotaSlice(4, 5).dup;
```

**Comment by 9il** [comment]
`dup` should have the same unqualified type. So, `slice` is more like `array`
