### ISSUE TITLE
remove Mir from DlangScience bountyscore

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#345]

**Comment by wilzbach** [comment]
FYI I am already in contact with them, but they take more than a week each time they reply :/

**Comment by 9il** [comment]
We have first bounty #213 for Mir, but DlangScience project

**Comment by 9il** [comment]
@wilzbach could you please give access to DlangSciense bountyscore? I will try it myself

**Comment by wilzbach** [comment]
> could you please give access to DlangSciense bountyscore

Done, but I think we depend on them to change it

**Comment by 9il** [comment]
I found solution: I just sent claim quiry for https://www.bountysource.com/teams/libmir :-)

**Comment by 9il** [comment]
@wilzbach you can now remove your bounty from  https://www.bountysource.com/teams/mir
