### ISSUE TITLE
Parallel mir.ndslice.algorithm

### ISSUE THREAD

**Issue by ljubobratovicrelja** [9il/dip80-ndslice#355]
Is there a way to run nd\* iterations in parallel?
##

**Comment by thewilsonator** [comment]
does std.parallelism not do the trick? 

Once dcompute gets to a useable state we can run OpenCL( and/or CUDA) kernels in parallel.

**Comment by ljubobratovicrelja** [comment]
> Once dcompute gets to a useable state we can run OpenCL( and/or CUDA) kernels in parallel.

Yep, looking forward to that! :)

> does std.parallelism not do the trick?

I'm not sure how to combine, say `ndEach` with `std.parallelism`.

**Comment by thewilsonator** [comment]
build an array of sub slices and then ndEach over them in parallel would be my guess.

**Comment by ljubobratovicrelja** [comment]
You mean something like:

``` d
auto s = iotaSlice(3, 3, 3).slice;
foreach (row; s.parallel)
    row.ndEach!((ref v) { ++v; });
```

Does the job, thanks! Will there be more elegant solution in future? Like an analog to `TaskPool.map` for `ndslice`...

**Comment by thewilsonator** [comment]
I don't know maybe @9il has some ideas, but given the recent [announcement](https://forum.dlang.org/thread/yhfbuxnrqkiqtvsnvngf@forum.dlang.org) was all single threaded it might be a while.

**Comment by thewilsonator** [comment]
Come to think of it it'll probably be a feature if Ilya's `nothrow @nogc` low level library.

**Comment by 9il** [comment]
Yes, I am looking forward `dcompute`. std.parallelism is only way for now.

**Comment by ljubobratovicrelja** [comment]
OK, cool. Tnx guys!

**Comment by 9il** [comment]
no plan to add the API into the main Mir repo. Maybe added to mir-algorithm in the future
