### ISSUE TITLE
what's the last mir dub version supporting dmd ?

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#358]

**Comment by thewilsonator** [comment]
0.17-aplha7. 1197033b8ba671551b766899cf25a8862cce88f7 removed support.

**Comment by thewilsonator** [comment]
@9il Perhaps this should go on the README.md in the compatibility section?

**Comment by 9il** [comment]
> 0.17-aplha7

`0.17-aplha9`

**Comment by 9il** [comment]
> @9il Perhaps this should go on the README.md in the compatibility section?

Yes

**Comment by timotheecour** [comment]
typo both here and in README:
0.17-aplha9
=>
0.17-alpha9
?

**Comment by 9il** [comment]
Yes

**Comment by timotheecour** [comment]
has this restriction been lifted? [cf recent forum discussions saying mir is now compatible with dmd] ? is mir HEAD  now compatible with dmd ?

**Comment by 9il** [comment]
Yes, Travis CI has DMD on
