### ISSUE TITLE
assumeSameStructure for packed slices

### ISSUE THREAD

**Issue by ljubobratovicrelja** [9il/dip80-ndslice#359]
I'd like to use `assumeSameStructure` to zip packed slices, but: `Error: static assert  "Packed slices not allowed in slice tuples"` - why's that? And is there a plan to support this in future? If not, is there a workaround?
##

**Comment by 9il** [comment]
> I'd like to use assumeSameStructure to zip packed slices, but: Error: static assert "Packed slices not allowed in slice tuples" - why's that?

Because it has low priority in my TODO.

You can use `mapSlice!identical` as workaround. This will make a slice not packed.

``` d
auto identical(T)(auto ref T a)
{
    return a;
}
```

**Comment by ljubobratovicrelja** [comment]
Awesome, thanks!

**Comment by 9il** [comment]
`zip` now supports packed slices if they all have the same shape packs.
