### ISSUE TITLE
Copy paste mistake in pairwise summation SIMD optimization

### ISSUE THREAD

**Issue by WalterWaldron** [9il/dip80-ndslice#360]
https://github.com/libmir/mir/blob/master/source/mir/sum.d#L883
I believe there's a copy paste mistake:
`v[0x0] += r[0x10];`...`v[0xF] += r[0x1F];`
where it should be:
`v[0x0] += v[0x10];`...`v[0xF] += v[0x1F];`

**Comment by 9il** [comment]
Thanks! Fixed in `v0.18.3`
