### ISSUE TITLE
Error: cannot append type int[] to type Slice!(2LU, int*)

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#381]
shouldn't this work?

```
unittest{
  auto a=[1,2,3,4].sliced(2,2);
  a~=[0,1];
}
```

what would be alternatives?

**Comment by 9il** [comment]
Concatenation is not implemented yet, see https://github.com/libmir/mir/issues/213

**Comment by 9il** [comment]
`concatenation` function for concatenation was added  http://docs.algorithm.dlang.io/latest/mir_ndslice_concatenation.html#.concatenation
