### ISSUE TITLE
regression test to make sure at least latest dub versions work? currently broken

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#387]
@9il 

adding these in a dub.json will result in:

`Root package lhd reference mir-algorithm ~>0.6.6 cannot be satisfied.`

```
"mir-algorithm": "~>0.6.6",
"mir": "~>1.1.0",
```

root cause:
https://github.com/libmir/mir/blob/master/dub.json contains:
```
"dependencies": {
        "mir-random": "~>0.2.1",
        "mir-algorithm": "~>0.4.1"
}
```

questions:

* do you know of a way to tell from dub failure logs (even with `dub --vverbose build`) that the root cause is mir's dub.json dependency on `mir-algorithm`? the way i arrived at conclusion was not efficient, i had to look at all my packages's recursive dependencies until looking at libmir's dub.json, which is not friendly at all  (it's of course a dub issue, not a mir issue, but I'm curious if u know of a way)

* could we have some kind of regression test to make sure things are buildable at least for latest published dub versions (given by `dub search mir*`) and get alerted when a PR or a commit breaks things before users run into this? I see rg `.travis.yml` but looks like this didn't test for this

**Comment by 9il** [comment]
fixed in v1.1.1.

> do you know of a way to tell from dub failure logs (even with dub --vverbose build) that the root cause is mir's dub.json dependency on mir-algorithm? the way i arrived at conclusion was not efficient, i had to look at all my packages's recursive dependencies until looking at libmir's dub.json, which is not friendly at all (it's of course a dub issue, not a mir issue, but I'm curious if u know of a way)

I don't know

> could we have some kind of regression test to make sure things are buildable at least for latest published dub versions (given by dub search mir*) and get alerted when a PR or a commit breaks things before users run into this? I see rg .travis.yml but looks like this didn't test for this

PRs are welcome. I do not know how to do it
