### ISSUE TITLE
mir-random does not compile with latest ldc on raspberry pi

### ISSUE THREAD

**Issue by gizmomogwai** [9il/dip80-ndslice#390]
../.dub/packages/mir-random-0.2.8/mir-random/source/mir/random/engine/package.d(267,32): Error: undefined identifier GETRANDOM, did you mean enum GET_RANDOM?
../.dub/packages/mir-random-0.2.8/mir-random/source/mir/random/engine/package.d(538,48): Error: template instance mir.random.engine.genRandomImplSysBlocking!() error instantiating
../.dub/packages/mir-random-0.2.8/mir-random/source/mir/random/engine/package.d(288,24): Error: undefined identifier GETRANDOM, did you mean enum GET_RANDOM?
../.dub/packages/mir-random-0.2.8/mir-random/source/mir/random/engine/package.d(612,51): Error: template instance mir.random.engine.genRandomImplSysNonBlocking!() error instantiating

seems like the syscall numbers are missing for raspberry pi.

**Comment by 9il** [comment]
@gizmomogwai Could you try to edit your local `dub.selections.json` with `~>master` for `mir-random` (needs a separate dependency). We added a workaround for now and want to know if it helps you. Thanks!

**Comment by gizmomogwai** [comment]
thanks a lot ... this seems to work. i found out in the end, that i can only use mir-algorithm instead of mir (which pulls in algorithm and random). but now the whole mir package seems to work!
i am using ldc2-1.5.0 for raspbian btw.

**Comment by 9il** [comment]
@gizmomogwai Please let me know if Mir is used in your company and we can put your companies' logo to Mir Algorithm similar to https://dlang.org/orgs-using-d.html

**Comment by gizmomogwai** [comment]
@9il, sorry I am only using mir in a hobby project of mine. Would be great if I find a place to use it at work! At the moment I am only using the linear interpolator, because mir came to my mind, when thinking if I should this implement from scratch or not. I am thinking about writing a little about the hobby project of mine, if I come to that, I will mention mir for sure!
