### ISSUE TITLE
How to reference the library

### ISSUE THREAD

**Issue by JohanEngelen** [9il/dip80-ndslice#394]
It'd be nice to tell people how you'd like them to reference the library in academic articles; then put that it the readme so it's easily found when viewing the github page.

@9il

**Comment by thewilsonator** [comment]
This would have been nice for the IWOCL paper i wrote (I just went with a URL reference to dcompute). Any ideas?

**Comment by 9il** [comment]
Hey Johan and Nicholas,

I did not write articles during a long time. Please feel free to make a PR.

Draft for /mir repo:
```
Name: Mir Library
Link: https://github.com/libmir/mir
Authors: Ilya Yaroshenko, Sebastian Wilzbach, Nathan Sashihara
```
Sebastian Wilzbach did mir.random.flex, Nathan Sashihara did huge work on mir.random in general.

**Comment by 9il** [comment]
Nicholas, feel free to choose how to cite dcompute.

**Comment by 9il** [comment]
Let me know when papers are published. Nice to see that our libraries are going to be cited

**Comment by thewilsonator** [comment]
Sorry I totally forgot about this: https://dl.acm.org/citation.cfm?doid=3204919.3204922

**Comment by 9il** [comment]
Thanks!
