### ISSUE TITLE
FFT?

### ISSUE THREAD

**Issue by andre2007** [9il/dip80-ndslice#395]
While searching on code.dlang.org for "FFT" the package MIR is shown as second result but I am not able find any FFT functionality in MIR or its related packages. 
Does MIR provide FFT functionality?

My goal is to execute the example from https://forum.dlang.org/thread/mlftojcqohcwxcordatz@forum.dlang.org faster than the python numpy variant. Calling the test function with sampling rate 10000 has a duration of 37 seconds for Python. LDC with all performance related stuff switched on has a duration of 41 seconds.
(On LDC even less numbers are calculated than on Numpy side as I reduce double x array to a length of power of 2, otherwise FFT in phobos fails)

**Comment by 9il** [comment]
Mir does not have fft
