### ISSUE TITLE
can't understand how `sliced` definition compiles

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#399]
@9il I don't understand how to parse this:

in mir-algorithm/source/mir/ndslice/slice.d
```d
Slice!(Iterator, N, kind)
    sliced
    (Iterator, size_t N, SliceKind kind)
    (Slice!(Iterator, 1, kind) slice, size_t[N] lengths...)
    if (N)
{ ... }
```

it looks like:
ReturnType sliced(args) (something_else) if(N) {...}

what is `(something_else)` ?

**Comment by dnadlinger** [comment]
`(args)` are the template parameters, `(something_else)` the actual parameters.

**Comment by 9il** [comment]
`sliced` has multiple declarations (edited). This definition construct an ND slice from 1-dimensional slice and shape `lengths`

**Comment by timotheecour** [comment]
sorry idk why i was confused
