### ISSUE TITLE
Failing on Buildkite

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#401]
https://buildkite.com/dlang/dmd/builds/5816#9f9df877-474e-4457-8f1d-91d21ae520a0

Looks like the newest release broke the build.

**Comment by wilzbach** [comment]
This is due to a dependency being updated and thus the backdoor being removed:

source/mir/sparse/package.d(452,12): Error: module `backdoor` is in file 'std/backdoor.d' which cannot be read

One easy way to fix this for the future once this has been adressed would be to commit the dub.selections.json to the source

**Comment by wilzbach** [comment]
Disabled temporarily: https://github.com/dlang/ci/pull/383

**Comment by 9il** [comment]
Thanks, fixed
