### ISSUE TITLE
mir.sparse multidimensional sparse arrays

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#43]
See #79

**Comment by wilzbach** [comment]
> Requires special fast index hash map implementation.
> Requires special fast index RB? tree implementation.

Maybe [emsi-containers](https://github.com/economicmodeling/containers)?
Why don't we use the builtin hashmap / rbtree for the initial version and then start the performance tuning? 

> Optimization is the root of all evil (Donald E. Knuth)

**Comment by 9il** [comment]
> Maybe emsi-containers?
> Why don't we use the builtin hashmap / rbtree for the initial version and then start the performance tuning?
1. They all are slow.
2. User can do it now with 10 lines of code. No reason to create a module. Containers are 99% of job.
