### ISSUE TITLE
mir.random: non-uniform random generators

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#46]
Non-uniform random generators. 
##

**Comment by wilzbach** [comment]
An overview of NumPy's capabilities can be found at the wiki 
https://github.com/DlangScience/mir/wiki/NumPy:-Random-sampling

**Comment by wilzbach** [comment]
> Have you start to collect article information for random distributions?

I wanted to get an initial feeling of what is required, therefore I played a bit with `mir.random`, e.g. yesterday I realized that I will probably need couple of `mir.stat` for the testing of the random api.

However WIP progress list of links to papers for distributions and source code of important implentations can be found at the [wiki](https://github.com/DlangScience/mir/wiki/Random-distributions). It will be updated gradually from now, but I do plan to select one algorithm/paper per distribution in the next two weeks :)
My learning plan is to do this for 3-4x rather easy distributions and then have a broader look at more generic solutions like Tinflex. Will keep you updated ;-)

**Comment by 9il** [comment]
Modules in `mir.random` package:
- [ ] `tinflex`
- [ ] `nonuniform` - collection of nonuniform rngs
- [ ] `itdr` - Inverse Transformed Density Rejection method
- [ ] `pinvcdf` - Polynomial interpolation
  of INVerse CDF

See also https://cran.r-project.org/web/packages/Runuran/index.html

**Comment by 9il** [comment]
Implemented in Mir Random
