### ISSUE TITLE
mir.data: sci data formats

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#47]
Use the new allocation api to support import and export into common file formats - e.g csv or Matlab 
##

**Comment by 9il** [comment]
hmm, maybe this should be `mir.format` package?

**Comment by wilzbach** [comment]
An overview of numpy's functionality can be found at the wiki 
https://github.com/DlangScience/mir/wiki/NumPy:-Input-and-output

**Comment by wilzbach** [comment]
> hmm, maybe this should be mir.format package?

I prefer io, if it's only about files (I like short names). Anyways I guess we will can discuss this once the functionality isis actually  there?

**Comment by 9il** [comment]
We should use current `std.stdio` or `std.file`. Also `std.io` would be included into phobos. So, this module would not contain functions to read files. For example: 

``` D
import std.file;
import mir.format;
auto slice = "filename".read.createSliceFromNumpyData;
```

**Comment by wilzbach** [comment]
> So, this module would mot contain functions to read files.

Convinced :)

**Comment by 9il** [comment]
The reason, that you may get data from network for example. So this, should be array/range based API to be able to integrate with phobos/vibe.d/future std.io

**Comment by 9il** [comment]
Oh, I found better option. What about `mir.data`?

**Comment by wilzbach** [comment]
> Oh, I found better option. What about mir.data?

+1 :)

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
