### ISSUE TITLE
mir.glas: linear algebra subroutines

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#48]
Common linear algebra functions. Probably this is part of the Blas integration? 

See the wiki for NumPy's capabilities: https://github.com/DlangScience/mir/wiki/NumPy:-Linear-algebra
##

**Comment by 9il** [comment]
Yes. `mir.las.sum` already implemented.

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
