### ISSUE TITLE
mir.stat: statistical functions 

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#49]
### TODO
- Probabilistic counting. See https://en.wikipedia.org/wiki/HyperLogLog

Statistical functions and algorithms. 

NumPy's capabilities:
https://github.com/DlangScience/mir/wiki/NumPy:-Statistics
##

**Comment by 9il** [comment]
> Maybe we can reuse parts from dstats?

We can reuse my `atmosphere`, but it is small. `dstats` has not BSL license :-/

**Comment by wilzbach** [comment]
> Each file contains a license header. All modules that are exclusively written by the main author (David Simcha) are licensed under the Boost license, so that pieces of them may freely be incorporated into Phobos 

(From dstats) 

I haven't checked details though.

**Comment by 9il** [comment]
OK, that is good :-)

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo

BTW,  https://github.com/tamediadigital/hll-d
