### ISSUE TITLE
mir.algorithm - Sorting, searching and counting 

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#50]
Ideally this would seamlessly integrate with the existing algorithms in Phobos from std.algorithm. 

I don't know what we do with new algorithms, but mir.algorithm sounds like a good place? 
At least sorting, partitioning, counting and searching should be checked. 

See also:
https://github.com/DlangScience/mir/wiki/NumPy:-Sorting,-searching,-and-counting

**Comment by 9il** [comment]
Probably this name would never be used. What you can place here?

**Comment by 9il** [comment]
Sorting, searching and counting can be done with std.algorithm. Any use case, which should be put here?

**Comment by wilzbach** [comment]
AFAIK phobos doesn't have any windowing function.

**Comment by 9il** [comment]
but ndslice already has `windows`

**Comment by wilzbach** [comment]
This issue is also about creating some documentation and tests that ensure that std.algorithm works fine with Ndslice - especially the documentation is important to users.

**Comment by wilzbach** [comment]
> but ndslice already has windows

Okay then this is only to write a guideguide or tutorial.

**Comment by 9il** [comment]
> This issue is also about creating some documentation and tests that ensure that std.algorithm works fine with Ndslice - especially the documentation is important to users.

The best option is `mir.ndslice.example` with a lot of unittests, which contains a 1-3 lines functions to cover numpy.

**Comment by 9il** [comment]
BTW, half of check boxes in our wiki about numpy should be turn on. They are 1-3 lines functions.

**Comment by 9il** [comment]
> BTW, half of check boxes in our wiki about numpy should be turn on. They are 1-3 lines functions.

However this is useless without examples

**Comment by wilzbach** [comment]
Closing in favor of #77 and #78

**Comment by wilzbach** [comment]
I found a good example in `ndslice` -  `median` (from the examples in package.d) could be part of such a package.

**Comment by 9il** [comment]
> I found a good example in ndslice - median (from the examples in package.d) could be part of such a package.

This would in filters or something specialized. algorithm assumes something general purposed
