### ISSUE TITLE
mir.dlang.io - create a new web presence 

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#51]
I own dlang.io, so we can use science.dlang.io or mir.dlang.io for a new web presence :) 
##

**Comment by 9il** [comment]
Awesome!

**Comment by wilzbach** [comment]
Btw `mir.rocks` is still available :)

**Comment by wilzbach** [comment]
FYI I reserved `mir.rocks` - seems like a good domain to start a blog, tutorial or guide.
Let me know if you have other ideas.

I manage domains via namecheap. You should have gotten invitations to dlang.io and mir.rocks - enjoy!

**Comment by 9il** [comment]
Awesome! Thanks a lot!

**Comment by wilzbach** [comment]
FYI both [`mir.rocks`](http://mir.rocks) and [`mir.dlang.io`](http://mir.dlang.io) now redirect to this Github repo (until we have time to find a better purpose)
