### ISSUE TITLE
mir.probcounting: hyperloglog algorithm implementation

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#54]
https://en.wikipedia.org/wiki/HyperLogLog

**Comment by wilzbach** [comment]
Can't we put this into the stat package? 
Probablistic counting seems to be a very specific feature and not so often used feature, so having its own first level package might not be justified.

**Comment by 9il** [comment]
> Probablistic counting seems to be a very specific feature and not so often used feature, so having its own first level package might not be justified.

This module would be used to process big data. In the same time, yes, `mir.stat` looks like proper place
