### ISSUE TITLE
aim: 100% code coverage

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#63]
I know it is quite silly to say that a templated D-code has 100% coverage. Nevertheless we should use the compiler's feature to detected unchecked branches and aim for 100% coverage soon.

My idea is that we then can enforce this requirement for all further code additions.

**Comment by wilzbach** [comment]
See also:

https://codecov.io/github/DlangScience/mir/source/mir/ndslice

https://codecov.io/github/DlangScience/mir/source/mir/las/sum.d?ref=e0ed6da37241ff3af2e6da348d9c6dea2201d801

**Comment by wilzbach** [comment]
#60, #61, #62 and #64 are small steps to this goal.

**Comment by 9il** [comment]
First I need https://github.com/D-Programming-Language/phobos/pull/4182 be merged. Then I will sync code with mir.

**Comment by 9il** [comment]
In the same time, this is not constraints for #64

**Comment by wilzbach** [comment]
Let's focus on this now, that there is a merge window for ndslice :)

**Comment by 9il** [comment]
nonono, good docs much more important. Current docs are brocken

**Comment by wilzbach** [comment]
> nonono, good docs much more important. Current docs are brocken

apparently the underscore didn't work :/

**Comment by 9il** [comment]
> apparently the underscore didn't work :/

Needs to add `--separator=_` for generator))

**Comment by wilzbach** [comment]
short update - just focusing on `ndslice` - the remaining spots are:

1) package.d see #156
2) [selection.d](https://codecov.io/github/DlangScience/mir/source/mir/ndslice/selection.d?ref=dc27bb8bfa651ed56c76a1a85e9cbc633d10fe2e#l-1050) - opIndex with packed 
3) [slice.d](https://codecov.io/github/DlangScience/mir/source/mir/ndslice/slice.d?ref=dc27bb8bfa651ed56c76a1a85e9cbc633d10fe2e) - a lot of stuff doesn't get checked for `PureN`

**Comment by wilzbach** [comment]
Update: only [slice.d](https://codecov.io/github/DlangScience/mir/source/mir/ndslice/slice.d?ref=dc27bb8bfa651ed56c76a1a85e9cbc633d10fe2e) left :)

**Comment by 9il** [comment]
Could you creat PR?
Then we will create `stable` branch and move code here. Than we will tag new release and i will push my uncovered code, hehe

**Comment by wilzbach** [comment]
see #161

> Than we will tag new release and i will push my uncovered code, hehe

Please use separate branches to work on your new features and only merge covered code ;-)
It is quite hard to go through uncovered, merged code and takes a lot of time, besides then we don't really need a stable branch, because `master` is stable :)

**Comment by 9il** [comment]
> Please use separate branches to work on your new features and only merge covered code ;-)
> It is quite hard to go through uncovered, merged code and takes a lot of time, besides then we don't really need a stable branch, because master is stable :)

I need documentation and coverage for unstable branch.

**Comment by 9il** [comment]
BTW, 99% is fine. I don't want to spend hours to cover few lines.

**Comment by wilzbach** [comment]
> BTW, 99% is fine. I don't want to spend hours to cover few lines.

Understood. I pushed you too hard - sorry :(

**Comment by 9il** [comment]
> Understood. I pushed you too hard - sorry :(

You have done a lot of work for Mir and I am really happy about that ;)
