### ISSUE TITLE
mir.bignum: hex/decimal integer/FP implementation

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#68]
https://github.com/andersonpd/eris
http://speleotrove.com/decimal/decarith.html
##

**Comment by wilzbach** [comment]
I just saw that there @WebDrake tried to push [Rational](https://github.com/WebDrake/Rational) to Phobos in 2013 - from the [discussion at this point](http://forum.dlang.org/thread/mailman.1747.1380128355.1719.digitalmars-d@puremagic.com?page=5): 

> > Probably because it wasn't proposed for review. I'm favorable to integrating it. (Andrei)
> > [...]
> > Me too.

@WebDrake: what happened? 

For [eris](https://github.com/andersonpd/eris/issues/6) there is a different issue:

> std.bigint is that CTFE is not available for the 32-bit Windows version. Because of this eris.decimal will not compile with std.bigint. The fundamental issue is that std.bigint uses assembly language routines for speed-up in the 32-bit Windows versions and asm instructions cannot be evaluated at compile time.

**Comment by WebDrake** [comment]
@wilzbach: Off the top of my head I don't remember all the details, but I think `Rational` stumbled over how (and whether) to handle `BigInt` as a supported type for numerator/denominator.

**Comment by WebDrake** [comment]
Re-reading that ancient discussion, I think I remember better: it was because `BigInt` really wasn't easy to get working right with `const` and `immutable`.

**Comment by 9il** [comment]
no plan to add the package into the main Mir repo
