### ISSUE TITLE
mir logo

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#76]
As using the "official D logo" doesn't make some parts of the community happy, I propose a couple of ideas for a custom _mir_ logo. This is round is just about finding 3-5 nice fonts that we want to try in the future. 

So this round is _not_ about criticizing the rocket (next round!), however don't hesitate to send me ideas for symbol(s) that could potentially represent mir.

You can [browse their rendered png version here](https://drive.google.com/folderview?id=0BwdiZp7qSaBhbGFmM0RiV200bms&usp=sharing) and find the [svg source here](https://drive.google.com/open?id=0BwdiZp7qSaBhZGlqQ21EYnJzTjg).
### Artwork

Atoms: https://commons.wikimedia.org/wiki/File:TBBTAtmBlack.svg (CC3 with attribution - there's a whole bunch of atom vector graphics - probably one which does't require republishing under CC. Alternatively we could draw this ourselves)
Rocket: https://pixabay.com/en/rocket-space-shuttle-ship-black-303886 (CC0 Public Domain: Free for commercial use, no attribution required)
Fonts: Probably we have to check once we shrunk down our selection - however fonts are usually pretty liberal.

Update: attached [ideas.zip](https://github.com/DlangScience/mir/files/213900/ideas.zip) for archiving purposes and mirror from Google Drive.

**Comment by wilzbach** [comment]
Pinging @9il  @John-Colvin @klickverbot @kyllingstad @BlackEdder @jansengb for their opinions

**Comment by BlackEdder** [comment]
I quite like the D with the atom for a general dlangscience logo. We could even keep the original colour then?

**Comment by 9il** [comment]
DlangScience logo should be discussed in gitter. I don't know if mir needs logo for now. May be after few packages be added.

**Comment by John-Colvin** [comment]
A logo for Mir is nice, but a logo for DlangScience in general is more urgent

**Comment by wilzbach** [comment]
> DlangScience logo should be discussed in gitter

Oh I am sorry, but since I changed my username I can no longer login to gittter. Can I go ahead and create an irc channel #dscience? It seems this is a bit more complicated as the channel was registered at some point, but then the user got removed from the network and now the freenode stuff is the owner. However we can contact them and it shouldn't be a big issue to "free" the channel, but I would need your permission and approval for that. After the acquisition I am happy to transfer the admin and/or founder rights to you. 

Btw If wanted we can link them irc and gittter with a bot.

**Comment by wilzbach** [comment]
> I quite like the D with the atom for a general dlangscience logo. We could even keep the original colour then?

Sure just depends on no one complaining to loud at the dlang community. @9il @John-Colvin what is your opinion about the [atom](https://drive.google.com/folderview?id=0BwdiZp7qSaBhbGFmM0RiV200bms&usp=sharing)?

> A logo for Mir is nice, but a logo for DlangScience in general is more urgent

Do you have other ideas than the atom or rocket? Maybe some math symbols?

**Comment by BlackEdder** [comment]
Could use \delta (or \Delta) instead of the D

**Comment by wilzbach** [comment]
> Could use \delta (or \Delta) instead of the D

Excellent idea - I went through my fonts and found these:
[Rendered pngs](https://drive.google.com/open?id=0BwdiZp7qSaBhdFlCaTdhZlotYXM)
[SVG](https://drive.google.com/open?id=0BwdiZp7qSaBhNzNndVd6ZUkwWTA)

Which do you like most? (I will state my favorites afterwards to avoid a bias)

Moreover I think that the atom looks pretty nice, but maybe people won't get the connection between the moons of Phobos and the atom, so maybe we should replace it with something else. How about small Pis at the position of the two moons? Other ideas?

**Comment by wilzbach** [comment]
Okay I picked the "creative" D and quickly tried a couple of colors.

<img src="https://cloud.githubusercontent.com/assets/4370550/14661721/97134406-06b8-11e6-8c88-cce3df808fea.png" width=300px height=300px />
<img src="https://cloud.githubusercontent.com/assets/4370550/14661723/97138038-06b8-11e6-8cb7-2f8460065766.png" width=300px height=300px />
<img src="https://cloud.githubusercontent.com/assets/4370550/14661724/9713e956-06b8-11e6-931c-7d1cc8badc19.png" width=300px height=300px />
<img src="https://cloud.githubusercontent.com/assets/4370550/14661720/97130cca-06b8-11e6-816c-4d66fa78b20a.png" width=300px height=300px />
<img src="https://cloud.githubusercontent.com/assets/4370550/14661722/9713ad92-06b8-11e6-9758-c773f5f67c08.png" width=300px height=300px />

[source](https://drive.google.com/folderview?id=0BwdiZp7qSaBhY2pIVklaMzRQS2M&usp=sharing)

**Comment by 9il** [comment]
Both Mir and DlangScience logos looks good now. Maybe we can just change color themes int the future.
