### ISSUE TITLE
NumPy users migration guide

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#77]
Started in #27 there exist are already a couple of wiki entries about NumPy's API. The main idea of this issue would be to complete this "cheatsheet" and create an guide for an easy migration from NumPy to mir.

This will probably be pending for a long time (as some functionality is still missing), but we shouldn't loose out of our focus. Creating a happy user base is important :)
##

**Comment by 9il** [comment]
https://github.com/ShigekiKarita/numir
