### ISSUE TITLE
#dscience-mir

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#80]
Hi, as you might know by now I went ahead and created [`#dscience`](https://kiwiirc.com/client/irc.freenode.net/dscience) and [`#dscience`](https://kiwiirc.com/client/irc.freenode.net/dscience) on freenode.

While I don't want to push IRC hard (I am fine with communication purely through Github), but I just wanted to know what your preferred communication channel is?

**Comment by 9il** [comment]
I will try to register

**Comment by wilzbach** [comment]
Did this work for you?

**Comment by 9il** [comment]
do you use OS X or linux?

**Comment by wilzbach** [comment]
Linux

**Comment by wilzbach** [comment]
Don't worry - as said we can still use Gitter or Github ;-)

**Comment by wilzbach** [comment]
Closing as gitter and github seems to work well for now :)
