### ISSUE TITLE
mir.combinatorics: behavior with tuples

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#92]
It doesn't compile yet with tuples (which we should fix) - and `only` returns a result in the same type:

```
import std.range: only;
auto projectionC = 2.permutations.indexedRoR(only('a', 1));
projection.front // [97, 1]
```

**Comment by 9il** [comment]
it is very rare case. Feel free to reopen it with clearer desciption

**Comment by wilzbach** [comment]
> it is very rare case. Feel free to reopen it with clearer desciption

Aren't tuples common in math?
E.g.

`
tuple(Variable1('a'), Variable2('b')).permutations
`

**Comment by 9il** [comment]
Maybe for tests. But we can use arrays.

**Comment by wilzbach** [comment]
the following works in python (both arrays and tuples), but not with `mir.combinatorics`, hence the motivation:

```
>>> from itertools import permutations
>>> list(permutations([1, 'A']))
[(1, 'A'), ('A', 1)]
>>> list(permutations((1, 'A')))
[(1, 'A'), ('A', 1)]
```

I know that there's [std.variant](https://dlang.org/phobos/std_variant.html), but it felt like a limitation of the combinatorics module.

**Comment by 9il** [comment]
This is overengineering for dlang
