### ISSUE TITLE
zero property functions should be const

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#93]
Dscanner will warn one if the `@property` attribute is provided it will warn you that a zero property function should be const. After all D supports (see below) and it yields a clearer API and avoids mistakes if the user tries to assign something to the `property functions`

``` D
size_t a()
{
 return _a;
}

size_t a(size_t a)
{
  return _a = a;
}
```

There is a bug in dscanner, that doesn't trigger warnings if the `@property` attribute is provided before the function name - so I suggest we keep this here as a reminder and try to tackle this once we have a 
bit of time and no open PRs at Phobos?

Maybe you have a "code quality" or "code style" tag?
##

**Comment by 9il** [comment]
@wilzbach BTW, you should be able to create labels and push PRs

**Comment by wilzbach** [comment]
> @wilzbach BTW, you should be able to create labels 

just saw it - will do so in the future :)

**Comment by 9il** [comment]
does not always true for generic dode
